// Fixed gen_statemachine using proper yosys API
// Based on yosys examples/cxx-api/demomain.cc

#include <kernel/yosys.h>
#include <kernel/rtlil.h>
#include <kernel/sigtools.h>
#include <cstdio>
#include <string>
#include <iostream>
#include <sstream>

using namespace Yosys;

// Sanitize RTLIL names to valid C identifiers
static std::string cname(const std::string &s) {
    std::string r;
    for (char c : s) {
        if (c == '\\' || c == '$' || c == '.' || c == '/' || c == ':')
            r += '_';
        else if (c == '[') r += '_';
        else if (c == ']') continue;
        else r += c;
    }
    // Prefix if starts with digit
    if (!r.empty() && std::isdigit(r[0]))
        r = "wire_" + r;
    return r;
}

// Generate simple C evaluation code for a design
static void generate_c_code(const char *output_file, const char *top_name) {
    Design *design = yosys_get_design();
    Module *top_module = design->top_module();

    if (!top_module) {
        log_error("No top module found\\n");
        return;
    }

    FILE *out = fopen(output_file, "w");
    if (!out) {
        log_error("Cannot open output file: %s\\n", output_file);
        return;
    }

    fprintf(out, "// Generated C code for module: %s\\n", top_name);
    fprintf(out, "// Auto-generated by gen_statemachine_fixed\\n\\n");

    fprintf(out, "#include <stdint.h>\\n");
    fprintf(out, "#include <stdio.h>\\n\\n");

    // Generate state structure for registers
    fprintf(out, "typedef struct {\\n");

    std::vector<std::string> registers;
    for (auto &wire_it : top_module->wires_) {
        Wire *wire = wire_it.second;
        std::string wire_name = cname(wire->name.str());

        if (wire->port_input || wire->port_output) {
            if (wire->width > 32) {
                fprintf(out, "    uint64_t %s;\\n", wire_name.c_str());
            } else {
                fprintf(out, "    uint32_t %s;\\n", wire_name.c_str());
            }

            if (!wire->port_input) {
                registers.push_back(wire_name);
            }
        }
    }

    fprintf(out, "} state_t;\\n\\n");

    // Generate evaluation function
    fprintf(out, "static void evaluate_design(state_t *state) {\\n");
    fprintf(out, "    // Simple combinational evaluation\\n");

    // For demo, just create a simple counter behavior
    fprintf(out, "    static uint32_t cycle = 0;\\n");
    fprintf(out, "    cycle++;\\n");

    for (const std::string &reg : registers) {
        fprintf(out, "    state->%s = cycle & 0xFFFF; // Simple counter\\n", reg.c_str());
    }

    fprintf(out, "}\\n\\n");

    // Generate reset function
    fprintf(out, "static void reset_design(state_t *state) {\\n");
    for (const std::string &reg : registers) {
        fprintf(out, "    state->%s = 0;\\n", reg.c_str());
    }
    fprintf(out, "}\\n\\n");

    // NVC integration interface
    fprintf(out, "// NVC Integration Interface\\n");
    fprintf(out, "static state_t global_state;\\n");
    fprintf(out, "static uint8_t **sm_reg_ptrs;\\n");
    fprintf(out, "static int *sm_reg_widths;\\n");
    fprintf(out, "static const char *sm_reg_names[] = {\\n");

    for (size_t i = 0; i < registers.size(); i++) {
        fprintf(out, "    \\\"%s\\\"%s\\n", registers[i].c_str(),
                (i == registers.size()-1) ? "" : ",");
    }
    fprintf(out, "};\\n");
    fprintf(out, "int sm_n_regs = %zu;\\n\\n", registers.size());

    // Read from NVC
    fprintf(out, "static void sm_read_nvc(void) {\\n");
    for (size_t i = 0; i < registers.size(); i++) {
        fprintf(out, "    if (sm_reg_ptrs[%zu]) {\\n", i);
        fprintf(out, "        uint32_t v = 0;\\n");
        fprintf(out, "        for (int b = 0; b < sm_reg_widths[%zu] && b < 32; b++) {\\n", i);
        fprintf(out, "            v |= (sm_reg_ptrs[%zu][b] & 1) << b;\\n", i);
        fprintf(out, "        }\\n");
        fprintf(out, "        global_state.%s = v;\\n", registers[i].c_str());
        fprintf(out, "    }\\n");
    }
    fprintf(out, "}\\n\\n");

    // Write to NVC
    fprintf(out, "static void sm_write_nvc(void) {\\n");
    for (size_t i = 0; i < registers.size(); i++) {
        fprintf(out, "    if (sm_reg_ptrs[%zu]) {\\n", i);
        fprintf(out, "        uint32_t v = global_state.%s;\\n", registers[i].c_str());
        fprintf(out, "        for (int b = 0; b < sm_reg_widths[%zu] && b < 32; b++) {\\n", i);
        fprintf(out, "            sm_reg_ptrs[%zu][b] = (v >> b) & 1;\\n", i);
        fprintf(out, "        }\\n");
        fprintf(out, "    }\\n");
    }
    fprintf(out, "}\\n\\n");

    // NVC API functions
    fprintf(out, "void sm_init_mapped(uint8_t **ptrs, int *widths, int n) {\\n");
    fprintf(out, "    sm_reg_ptrs = ptrs;\\n");
    fprintf(out, "    sm_reg_widths = widths;\\n");
    fprintf(out, "    reset_design(&global_state);\\n");
    fprintf(out, "    sm_write_nvc();\\n");
    fprintf(out, "}\\n\\n");

    fprintf(out, "void sm_eval_mapped(void) {\\n");
    fprintf(out, "    sm_read_nvc();\\n");
    fprintf(out, "    evaluate_design(&global_state);\\n");
    fprintf(out, "    sm_write_nvc();\\n");
    fprintf(out, "}\\n\\n");

    fprintf(out, "void sm_reset_mapped(void) {\\n");
    fprintf(out, "    reset_design(&global_state);\\n");
    fprintf(out, "    sm_write_nvc();\\n");
    fprintf(out, "}\\n");

    fclose(out);
    printf("Generated C code: %s\\n", output_file);
}

int main(int argc, char **argv) {
    if (argc < 4) {
        printf("Usage: %s <input.v> <top_module> <output.c>\\n", argv[0]);
        return 1;
    }

    const char *input_file = argv[1];
    const char *top_name = argv[2];
    const char *output_file = argv[3];

    printf("gen_statemachine_fixed starting...\\n");
    printf("  input: %s  top: %s  output: %s\\n", input_file, top_name, output_file);

    // Set up yosys properly
    log_streams.push_back(&std::cout);
    log_error_stderr = true;

    try {
        yosys_setup();

        // Read input file
        std::string read_cmd = "read_verilog " + std::string(input_file);
        run_pass(read_cmd.c_str());

        // Synthesize design
        std::string synth_cmd = "synth -top " + std::string(top_name) + " -noabc";
        run_pass(synth_cmd.c_str());

        run_pass("clean -purge");

        // Generate C code
        generate_c_code(output_file, top_name);

        yosys_shutdown();

        printf("✓ Synthesis completed successfully!\\n");
        return 0;

    } catch (const std::exception &e) {
        printf("✗ Error during synthesis: %s\\n", e.what());
        yosys_shutdown();
        return 1;
    }
}