/* gen_netlist.c — Netlist generator for RTL simulation testing.
 *
 * Generates various test circuits in the gate descriptor format
 * used by the parallel RTL simulation engine.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "rtl_sim_engine.h"

static void print_usage(const char *prog) {
    printf("Usage: %s <circuit_type> [options]\n");
    printf("Circuit types:\n");
    printf("  adder <width>     - Ripple-carry adder\n");
    printf("  counter <width>   - Binary counter\n");
    printf("  shift <width>     - Shift register\n");
    printf("  lfsr <width>      - Linear feedback shift register\n");
}

static int generate_adder(const char *filename, int width) {
    FILE *f = fopen(filename, "w");
    if (!f) {
        perror(filename);
        return -1;
    }

    fprintf(f, "# %d-bit ripple-carry adder netlist\n", width);
    fprintf(f, "# Generated by gen_netlist\n\n");

    fprintf(f, "WIDTH %d\n", width);
    fprintf(f, "INPUTS %d\n", 2 * width + 1);  // A, B, carry_in
    fprintf(f, "OUTPUTS %d\n", width + 1);     // sum, carry_out
    fprintf(f, "STATE_SIZE %d\n", 300 + width * 10);

    fprintf(f, "\n# Input assignments:\n");
    for (int i = 0; i < width; i++) {
        fprintf(f, "# A[%d] = state[%d]\n", i, i);
    }
    for (int i = 0; i < width; i++) {
        fprintf(f, "# B[%d] = state[%d]\n", i, width + i);
    }
    fprintf(f, "# carry_in = state[%d]\n", 2 * width);

    fprintf(f, "\n# Output assignments:\n");
    for (int i = 0; i < width; i++) {
        fprintf(f, "# sum[%d] = state[%d]\n", i, 100 + i);
    }
    fprintf(f, "# carry_out = state[%d]\n", 100 + width);

    fprintf(f, "\n# Gates:\n");

    int gate_id = 0;
    for (int i = 0; i < width; i++) {
        int a_bit = i;
        int b_bit = width + i;
        int carry_in = (i == 0) ? (2 * width) : (200 + (i-1));
        int sum_out = 100 + i;
        int carry_out = 200 + i;
        int temp_xor = 300 + i * 3 + 0;
        int temp_and1 = 300 + i * 3 + 1;
        int temp_and2 = 300 + i * 3 + 2;

        // a XOR b
        fprintf(f, "GATE %d XOR 2 %d %d %d\n", gate_id++, temp_xor, a_bit, b_bit);

        // sum = (a XOR b) XOR carry_in
        fprintf(f, "GATE %d XOR 2 %d %d %d\n", gate_id++, sum_out, temp_xor, carry_in);

        // a AND b
        fprintf(f, "GATE %d AND 2 %d %d %d\n", gate_id++, temp_and1, a_bit, b_bit);

        // (a XOR b) AND carry_in
        fprintf(f, "GATE %d AND 2 %d %d %d\n", gate_id++, temp_and2, temp_xor, carry_in);

        // carry_out = (a AND b) OR ((a XOR b) AND carry_in)
        fprintf(f, "GATE %d OR 2 %d %d %d\n", gate_id++, carry_out, temp_and1, temp_and2);
    }

    // Copy final carry to output
    fprintf(f, "GATE %d BUF 1 %d %d\n", gate_id++, 100 + width, 200 + width - 1);

    fclose(f);
    printf("Generated %d-bit adder: %d gates\n", width, gate_id);
    return 0;
}

static int generate_counter(const char *filename, int width) {
    FILE *f = fopen(filename, "w");
    if (!f) {
        perror(filename);
        return -1;
    }

    fprintf(f, "# %d-bit binary counter netlist\n", width);
    fprintf(f, "# Uses T flip-flops: Q_next = Q XOR T\n\n");

    fprintf(f, "WIDTH %d\n", width);
    fprintf(f, "INPUTS 2\n");          // clock, enable
    fprintf(f, "OUTPUTS %d\n", width); // counter output
    fprintf(f, "STATE_SIZE %d\n", 100 + width * 2);

    fprintf(f, "\n# Input assignments:\n");
    fprintf(f, "# enable = state[0]\n");
    fprintf(f, "# clock = state[1]\n");

    fprintf(f, "\n# State assignments:\n");
    for (int i = 0; i < width; i++) {
        fprintf(f, "# count[%d] = state[%d]\n", i, 10 + i);
    }

    fprintf(f, "\n# Gates:\n");

    int gate_id = 0;

    // Generate T flip-flop chain
    for (int i = 0; i < width; i++) {
        int q_current = 10 + i;
        int q_next = 50 + i;
        int t_input;

        if (i == 0) {
            // LSB toggles with enable
            t_input = 0; // enable signal
        } else {
            // Higher bits toggle when all lower bits are 1
            t_input = 80 + i - 1; // AND of all lower bits
        }

        // T flip-flop: Q_next = Q XOR T
        fprintf(f, "GATE %d XOR 2 %d %d %d\n", gate_id++, q_next, q_current, t_input);

        // Generate AND chain for higher bits
        if (i > 0) {
            if (i == 1) {
                // AND of enable and Q[0]
                fprintf(f, "GATE %d AND 2 %d %d %d\n", gate_id++, 80 + i - 1, 0, 10);
            } else {
                // AND of previous AND result and Q[i-1]
                fprintf(f, "GATE %d AND 2 %d %d %d\n", gate_id++, 80 + i - 1, 80 + i - 2, 10 + i - 1);
            }
        }

        // Clock the flip-flop (simplified - just copy next to current on clock edge)
        fprintf(f, "GATE %d DFF 1 %d %d\n", gate_id++, q_current, q_next);
    }

    fclose(f);
    printf("Generated %d-bit counter: %d gates\n", width, gate_id);
    return 0;
}

static int generate_lfsr(const char *filename, int width) {
    FILE *f = fopen(filename, "w");
    if (!f) {
        perror(filename);
        return -1;
    }

    // Use standard LFSR tap positions for common widths
    int taps[32] = {0}; // Tap positions (1-indexed)
    int num_taps = 0;

    switch (width) {
        case 4:  taps[0] = 4; taps[1] = 3; num_taps = 2; break;
        case 8:  taps[0] = 8; taps[1] = 6; taps[2] = 5; taps[3] = 4; num_taps = 4; break;
        case 16: taps[0] = 16; taps[1] = 15; taps[2] = 13; taps[3] = 4; num_taps = 4; break;
        case 32: taps[0] = 32; taps[1] = 22; taps[2] = 2; taps[3] = 1; num_taps = 4; break;
        default:
            // Default: use width and width-1
            taps[0] = width;
            taps[1] = width - 1;
            num_taps = 2;
            break;
    }

    fprintf(f, "# %d-bit LFSR netlist\n", width);
    fprintf(f, "# Taps at positions:");
    for (int i = 0; i < num_taps; i++) {
        fprintf(f, " %d", taps[i]);
    }
    fprintf(f, "\n\n");

    fprintf(f, "WIDTH %d\n", width);
    fprintf(f, "INPUTS 1\n");          // clock
    fprintf(f, "OUTPUTS %d\n", width); // LFSR state
    fprintf(f, "STATE_SIZE %d\n", 100);

    fprintf(f, "\n# State assignments:\n");
    for (int i = 0; i < width; i++) {
        fprintf(f, "# lfsr[%d] = state[%d]\n", i, 10 + i);
    }

    fprintf(f, "\n# Gates:\n");

    int gate_id = 0;

    // Generate feedback XOR
    int feedback = 50; // Feedback signal
    if (num_taps > 1) {
        // XOR first two taps
        fprintf(f, "GATE %d XOR 2 %d %d %d\n", gate_id++, 51,
                10 + taps[0] - 1, 10 + taps[1] - 1);

        // XOR with remaining taps
        for (int i = 2; i < num_taps; i++) {
            fprintf(f, "GATE %d XOR 2 %d %d %d\n", gate_id++, 51 + i - 1,
                    51 + i - 2, 10 + taps[i] - 1);
        }
        feedback = 51 + num_taps - 2;
    } else {
        // Single tap
        feedback = 10 + taps[0] - 1;
    }

    // Generate shift register with feedback
    for (int i = 0; i < width; i++) {
        int current = 10 + i;
        int next;

        if (i == 0) {
            // LSB gets feedback
            next = feedback;
        } else {
            // Other bits shift from previous
            next = 10 + i - 1;
        }

        // D flip-flop
        fprintf(f, "GATE %d DFF 1 %d %d\n", gate_id++, current, next);
    }

    fclose(f);
    printf("Generated %d-bit LFSR: %d gates\n", width, gate_id);
    return 0;
}

int main(int argc, char **argv) {
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    const char *circuit_type = argv[1];
    char filename[256];

    if (strcmp(circuit_type, "adder") == 0) {
        int width = (argc > 2) ? atoi(argv[2]) : 8;
        snprintf(filename, sizeof(filename), "adder_%d.netlist", width);
        return generate_adder(filename, width);
    }
    else if (strcmp(circuit_type, "counter") == 0) {
        int width = (argc > 2) ? atoi(argv[2]) : 8;
        snprintf(filename, sizeof(filename), "counter_%d.netlist", width);
        return generate_counter(filename, width);
    }
    else if (strcmp(circuit_type, "lfsr") == 0) {
        int width = (argc > 2) ? atoi(argv[2]) : 8;
        snprintf(filename, sizeof(filename), "lfsr_%d.netlist", width);
        return generate_lfsr(filename, width);
    }
    else {
        fprintf(stderr, "Unknown circuit type: %s\n", circuit_type);
        print_usage(argv[0]);
        return 1;
    }
}