create_clock -name clk -period 20.000 [get_ports clk]
# `phase` is generated by toggling on every clk edge → period = 2 * clk
create_generated_clock -name phase -source [get_ports clk] -divide_by 2 [get_registers phase]
derive_pll_clocks
derive_clock_uncertainty
