-- th22_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th22_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th22_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 29) := (
    -6.317732e-02, +5.885632e-01, -7.389983e-02, -1.867839e-01, -2.344588e-01, +4.033927e-01,
    -2.233375e-01, +2.288679e-01, -1.466294e-01, -1.630604e-01, +5.932574e-01, +5.560420e-01,
    +3.489923e-01, -7.714210e-01, -3.123014e-02, +7.534885e-01, -6.506052e-01, -4.517190e-01,
    -5.679727e-01, -3.901579e-01, -1.213416e+00, +5.961364e-01, -7.130239e-01, +3.611633e-01,
    -7.771186e-02, +7.289060e-01, -8.197737e-01, -7.900918e-01, -1.160225e-02, +1.621992e-01
  );
  constant drive_b1 : real_vector(0 to 9) := (
    +6.216898e-03, +9.206813e-03, +1.350325e-02, +7.494900e-02, +4.846868e-01, +9.952895e-03,
    +6.080702e-01, +1.422320e+00, -1.991599e-03, +6.903341e-02
  );
  constant drive_W2 : real_vector(0 to 9) := (
    -1.307438e-05, -9.992909e-06, -7.541867e-06, -8.175005e-06, +6.095961e-06, -1.084126e-05,
    +8.841566e-06, +1.651747e-05, -1.659845e-06, -1.598033e-06
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => +1.183707e-05);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b : integer := 0;
    variable z_a_new, z_b_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 9);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b then
        z_a := z_a_new;
        z_b := z_b_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*V_X_v + drive_W1(10)*A.voltage + drive_W1(20)*B.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*V_X_v + drive_W1(11)*A.voltage + drive_W1(21)*B.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*V_X_v + drive_W1(12)*A.voltage + drive_W1(22)*B.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*V_X_v + drive_W1(13)*A.voltage + drive_W1(23)*B.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*V_X_v + drive_W1(14)*A.voltage + drive_W1(24)*B.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*V_X_v + drive_W1(15)*A.voltage + drive_W1(25)*B.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*V_X_v + drive_W1(16)*A.voltage + drive_W1(26)*B.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*V_X_v + drive_W1(17)*A.voltage + drive_W1(27)*B.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*V_X_v + drive_W1(18)*A.voltage + drive_W1(28)*B.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*V_X_v + drive_W1(19)*A.voltage + drive_W1(29)*B.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Inverter rule with HOLD zone (completion detection). Only
          -- commit V(Y) to a rail when V(X) is clearly past the PMOS/NMOS
          -- threshold. In between (ACTIVE zone) keep the previous v_y —
          -- this is the event-driven analogue of "the physical inverter
          -- is still mid-transition, so the downstream gate shouldn't
          -- see a new rail yet". Without this the cell snaps to a rail
          -- on every partial input change and the keeper locks it in
          -- prematurely, breaking multi-stage NCL cascades.
          if V_X_v < VTN then
            v_y := vdd_v;
          elsif V_X_v > vdd_v - VTP_ABS then
            v_y := 0.0;
          -- else: hold previous v_y
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
