-- th22_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th22_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th22_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 127) := (
    -4.623441e-02, +1.507369e+00, -1.299447e+00, -3.526656e-01, -1.365814e-01, -9.323037e-01,
    +1.577294e+00, +4.412007e-01, -1.475346e-01, -1.856885e-01, -7.143160e-02, +5.156629e-01,
    +4.443643e-01, -2.782834e-01, +8.449347e-01, +4.517798e-01, -4.022432e-01, +2.626007e-01,
    -5.723995e-01, -3.866260e-01, -5.540852e-01, -8.397805e-01, -4.115451e-01, +1.253628e+00,
    +1.686158e-01, -1.816085e+00, -7.543845e-01, -2.192963e-01, -3.335691e-01, +5.511726e-01,
    -4.617049e-01, +4.814069e-01, -2.813322e-01, -1.309342e+00, +1.605898e+00, -2.367544e-01,
    -1.046770e-02, +2.141074e+00, -4.616066e-01, +2.090858e-02, +3.352157e-02, +2.069496e-02,
    -2.126703e+00, +6.473594e-03, +2.756635e+00, -4.611123e-01, +3.395039e-01, +7.612763e-01,
    -1.889011e-01, +7.510038e-01, +2.215133e-01, -3.589847e-01, +1.684245e-02, +5.832556e-01,
    -2.089407e+00, +1.088150e-01, +3.454669e-01, +1.417702e-02, +4.337686e-01, +1.978213e-02,
    +9.144258e-01, +2.551955e-02, +2.868961e-02, -5.875512e-02, -1.780715e-01, -1.344183e+00,
    +9.870845e-01, +2.331247e-01, -3.967464e-01, -1.033802e+00, +1.794069e+00, -2.997932e+00,
    -1.391234e-01, -2.986783e-02, +1.419776e+00, -1.615723e+00, -6.823770e-01, -1.118904e-01,
    -1.386210e+00, +2.314467e-01, -1.299513e-01, +2.156253e+00, +1.088593e-01, -3.659940e-02,
    -5.681089e-02, -1.198459e+00, -6.877560e-01, -9.631148e-01, +1.795789e-01, +1.129325e+00,
    -8.201933e-03, +1.697133e+00, -1.521228e+00, +4.065512e-01, +2.441932e-03, +3.956451e-01,
    -3.825398e-01, +4.719539e-01, -1.153661e+00, -6.127355e-01, -9.166514e-02, -8.985413e-01,
    -2.302897e+00, +2.106378e+00, -2.493351e-01, -1.864508e-01, +1.869621e+00, -1.738718e+00,
    -1.593795e+00, -6.035709e-02, +1.460128e+00, +7.482413e-01, -3.084406e-01, -1.041971e+00,
    +7.155183e-03, -3.159895e-01, +7.531174e-02, +3.647153e-01, +1.618688e+00, +1.198568e+00,
    +2.362071e-01, -6.081103e-01, -3.456522e-02, -1.778519e+00, +4.397680e-01, +1.079742e+00,
    -6.430970e-01, +1.082975e+00
  );
  constant drive_b1 : real_vector(0 to 31) := (
    -1.734699e-02, +2.518690e-01, +8.732502e-02, -7.968510e-02, +1.143769e-04, -8.944362e-01,
    -3.053698e-01, +8.664649e-01, -4.910112e-05, -2.311315e-04, -3.789317e+00, +3.076745e+00,
    +1.230879e+00, -4.421351e-04, -8.281936e-01, -3.046539e-01, -5.200381e-04, -1.110182e+00,
    +1.161458e-03, -7.893280e-05, +9.022847e-04, +1.022689e+00, -1.172624e+00, -1.694530e+00,
    -1.003960e-01, +1.581118e+00, -3.182963e-04, -3.344145e-01, -1.295175e-01, -5.045486e-01,
    +1.544357e-03, -4.465623e-01
  );
  constant drive_W2 : real_vector(0 to 31) := (
    -5.171535e-06, +2.219239e-05, -2.129820e-05, +2.241712e-06, +3.778043e-07, -2.739854e-05,
    +2.553795e-05, +2.875425e-05, -1.846437e-07, -8.009756e-07, +4.697927e-05, -3.575304e-05,
    +2.656790e-05, -1.528968e-06, -1.627945e-05, -1.020020e-05, -1.802644e-06, -1.871865e-05,
    +3.767053e-06, -3.472345e-07, +2.912127e-06, -1.697808e-05, -2.940684e-05, -2.038331e-05,
    -3.963587e-06, +2.439740e-05, -1.164806e-06, -2.316991e-05, -1.799402e-05, -1.119145e-05,
    +5.038418e-06, -1.045592e-05
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => +3.010130e-06);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b : integer := 0;
    variable z_a_new, z_b_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 31);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b then
        z_a := z_a_new;
        z_b := z_b_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*vdd_v + drive_W1(32)*V_X_v + drive_W1(64)*A.voltage + drive_W1(96)*B.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*vdd_v + drive_W1(33)*V_X_v + drive_W1(65)*A.voltage + drive_W1(97)*B.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*vdd_v + drive_W1(34)*V_X_v + drive_W1(66)*A.voltage + drive_W1(98)*B.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*vdd_v + drive_W1(35)*V_X_v + drive_W1(67)*A.voltage + drive_W1(99)*B.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*vdd_v + drive_W1(36)*V_X_v + drive_W1(68)*A.voltage + drive_W1(100)*B.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*vdd_v + drive_W1(37)*V_X_v + drive_W1(69)*A.voltage + drive_W1(101)*B.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*vdd_v + drive_W1(38)*V_X_v + drive_W1(70)*A.voltage + drive_W1(102)*B.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*vdd_v + drive_W1(39)*V_X_v + drive_W1(71)*A.voltage + drive_W1(103)*B.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*vdd_v + drive_W1(40)*V_X_v + drive_W1(72)*A.voltage + drive_W1(104)*B.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*vdd_v + drive_W1(41)*V_X_v + drive_W1(73)*A.voltage + drive_W1(105)*B.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*vdd_v + drive_W1(42)*V_X_v + drive_W1(74)*A.voltage + drive_W1(106)*B.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*vdd_v + drive_W1(43)*V_X_v + drive_W1(75)*A.voltage + drive_W1(107)*B.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        z_drive(12) := drive_W1(12)*vdd_v + drive_W1(44)*V_X_v + drive_W1(76)*A.voltage + drive_W1(108)*B.voltage + drive_b1(12);
        if z_drive(12) > 0.0 then h_drive(12) := z_drive(12); else h_drive(12) := 0.01 * z_drive(12); end if;
        z_drive(13) := drive_W1(13)*vdd_v + drive_W1(45)*V_X_v + drive_W1(77)*A.voltage + drive_W1(109)*B.voltage + drive_b1(13);
        if z_drive(13) > 0.0 then h_drive(13) := z_drive(13); else h_drive(13) := 0.01 * z_drive(13); end if;
        z_drive(14) := drive_W1(14)*vdd_v + drive_W1(46)*V_X_v + drive_W1(78)*A.voltage + drive_W1(110)*B.voltage + drive_b1(14);
        if z_drive(14) > 0.0 then h_drive(14) := z_drive(14); else h_drive(14) := 0.01 * z_drive(14); end if;
        z_drive(15) := drive_W1(15)*vdd_v + drive_W1(47)*V_X_v + drive_W1(79)*A.voltage + drive_W1(111)*B.voltage + drive_b1(15);
        if z_drive(15) > 0.0 then h_drive(15) := z_drive(15); else h_drive(15) := 0.01 * z_drive(15); end if;
        z_drive(16) := drive_W1(16)*vdd_v + drive_W1(48)*V_X_v + drive_W1(80)*A.voltage + drive_W1(112)*B.voltage + drive_b1(16);
        if z_drive(16) > 0.0 then h_drive(16) := z_drive(16); else h_drive(16) := 0.01 * z_drive(16); end if;
        z_drive(17) := drive_W1(17)*vdd_v + drive_W1(49)*V_X_v + drive_W1(81)*A.voltage + drive_W1(113)*B.voltage + drive_b1(17);
        if z_drive(17) > 0.0 then h_drive(17) := z_drive(17); else h_drive(17) := 0.01 * z_drive(17); end if;
        z_drive(18) := drive_W1(18)*vdd_v + drive_W1(50)*V_X_v + drive_W1(82)*A.voltage + drive_W1(114)*B.voltage + drive_b1(18);
        if z_drive(18) > 0.0 then h_drive(18) := z_drive(18); else h_drive(18) := 0.01 * z_drive(18); end if;
        z_drive(19) := drive_W1(19)*vdd_v + drive_W1(51)*V_X_v + drive_W1(83)*A.voltage + drive_W1(115)*B.voltage + drive_b1(19);
        if z_drive(19) > 0.0 then h_drive(19) := z_drive(19); else h_drive(19) := 0.01 * z_drive(19); end if;
        z_drive(20) := drive_W1(20)*vdd_v + drive_W1(52)*V_X_v + drive_W1(84)*A.voltage + drive_W1(116)*B.voltage + drive_b1(20);
        if z_drive(20) > 0.0 then h_drive(20) := z_drive(20); else h_drive(20) := 0.01 * z_drive(20); end if;
        z_drive(21) := drive_W1(21)*vdd_v + drive_W1(53)*V_X_v + drive_W1(85)*A.voltage + drive_W1(117)*B.voltage + drive_b1(21);
        if z_drive(21) > 0.0 then h_drive(21) := z_drive(21); else h_drive(21) := 0.01 * z_drive(21); end if;
        z_drive(22) := drive_W1(22)*vdd_v + drive_W1(54)*V_X_v + drive_W1(86)*A.voltage + drive_W1(118)*B.voltage + drive_b1(22);
        if z_drive(22) > 0.0 then h_drive(22) := z_drive(22); else h_drive(22) := 0.01 * z_drive(22); end if;
        z_drive(23) := drive_W1(23)*vdd_v + drive_W1(55)*V_X_v + drive_W1(87)*A.voltage + drive_W1(119)*B.voltage + drive_b1(23);
        if z_drive(23) > 0.0 then h_drive(23) := z_drive(23); else h_drive(23) := 0.01 * z_drive(23); end if;
        z_drive(24) := drive_W1(24)*vdd_v + drive_W1(56)*V_X_v + drive_W1(88)*A.voltage + drive_W1(120)*B.voltage + drive_b1(24);
        if z_drive(24) > 0.0 then h_drive(24) := z_drive(24); else h_drive(24) := 0.01 * z_drive(24); end if;
        z_drive(25) := drive_W1(25)*vdd_v + drive_W1(57)*V_X_v + drive_W1(89)*A.voltage + drive_W1(121)*B.voltage + drive_b1(25);
        if z_drive(25) > 0.0 then h_drive(25) := z_drive(25); else h_drive(25) := 0.01 * z_drive(25); end if;
        z_drive(26) := drive_W1(26)*vdd_v + drive_W1(58)*V_X_v + drive_W1(90)*A.voltage + drive_W1(122)*B.voltage + drive_b1(26);
        if z_drive(26) > 0.0 then h_drive(26) := z_drive(26); else h_drive(26) := 0.01 * z_drive(26); end if;
        z_drive(27) := drive_W1(27)*vdd_v + drive_W1(59)*V_X_v + drive_W1(91)*A.voltage + drive_W1(123)*B.voltage + drive_b1(27);
        if z_drive(27) > 0.0 then h_drive(27) := z_drive(27); else h_drive(27) := 0.01 * z_drive(27); end if;
        z_drive(28) := drive_W1(28)*vdd_v + drive_W1(60)*V_X_v + drive_W1(92)*A.voltage + drive_W1(124)*B.voltage + drive_b1(28);
        if z_drive(28) > 0.0 then h_drive(28) := z_drive(28); else h_drive(28) := 0.01 * z_drive(28); end if;
        z_drive(29) := drive_W1(29)*vdd_v + drive_W1(61)*V_X_v + drive_W1(93)*A.voltage + drive_W1(125)*B.voltage + drive_b1(29);
        if z_drive(29) > 0.0 then h_drive(29) := z_drive(29); else h_drive(29) := 0.01 * z_drive(29); end if;
        z_drive(30) := drive_W1(30)*vdd_v + drive_W1(62)*V_X_v + drive_W1(94)*A.voltage + drive_W1(126)*B.voltage + drive_b1(30);
        if z_drive(30) > 0.0 then h_drive(30) := z_drive(30); else h_drive(30) := 0.01 * z_drive(30); end if;
        z_drive(31) := drive_W1(31)*vdd_v + drive_W1(63)*V_X_v + drive_W1(95)*A.voltage + drive_W1(127)*B.voltage + drive_b1(31);
        if z_drive(31) > 0.0 then h_drive(31) := z_drive(31); else h_drive(31) := 0.01 * z_drive(31); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_W2(12)*h_drive(12) + drive_W2(13)*h_drive(13) + drive_W2(14)*h_drive(14) + drive_W2(15)*h_drive(15) + drive_W2(16)*h_drive(16) + drive_W2(17)*h_drive(17) + drive_W2(18)*h_drive(18) + drive_W2(19)*h_drive(19) + drive_W2(20)*h_drive(20) + drive_W2(21)*h_drive(21) + drive_W2(22)*h_drive(22) + drive_W2(23)*h_drive(23) + drive_W2(24)*h_drive(24) + drive_W2(25)*h_drive(25) + drive_W2(26)*h_drive(26) + drive_W2(27)*h_drive(27) + drive_W2(28)*h_drive(28) + drive_W2(29)*h_drive(29) + drive_W2(30)*h_drive(30) + drive_W2(31)*h_drive(31) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Inverter rule with HOLD zone (completion detection). Only
          -- commit V(Y) to a rail when V(X) is clearly past the PMOS/NMOS
          -- threshold. In between (ACTIVE zone) keep the previous v_y —
          -- this is the event-driven analogue of "the physical inverter
          -- is still mid-transition, so the downstream gate shouldn't
          -- see a new rail yet". Without this the cell snaps to a rail
          -- on every partial input change and the keeper locks it in
          -- prematurely, breaking multi-stage NCL cascades.
          if V_X_v < VTN then
            v_y := vdd_v;
          elsif V_X_v > vdd_v - VTP_ABS then
            v_y := 0.0;
          -- else: hold previous v_y
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
