-- th22_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th22_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th22_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 127) := (
    -5.150484e-02, +1.425521e+00, -1.299678e+00, -2.867984e-01, -1.364374e-01, -7.890024e-01,
    +1.697127e+00, +5.489524e-01, -1.476061e-01, -1.859987e-01, -1.022655e-01, +4.956707e-01,
    +5.627388e-01, -2.788731e-01, +5.899247e-01, +5.285238e-01, -4.029403e-01, +3.096011e-01,
    -5.709352e-01, -3.867547e-01, -5.529532e-01, -8.482134e-01, -4.627605e-01, +1.537137e+00,
    +1.860966e-01, -1.844873e+00, -7.548403e-01, -2.938989e-01, -5.864221e-01, +6.499193e-01,
    -4.597411e-01, +4.977661e-01, -2.804410e-01, -1.404099e+00, +1.747116e+00, -2.659276e-01,
    -1.058363e-02, +1.903338e+00, -4.772807e-01, +2.366289e-02, +3.359117e-02, +2.097059e-02,
    -2.159632e+00, +1.919583e-02, +2.985125e+00, -4.605877e-01, +4.416472e-01, +8.685305e-01,
    -1.882801e-01, +7.993476e-01, +2.202456e-01, -3.588580e-01, +1.586703e-02, +1.138852e+00,
    -2.178907e+00, -1.861244e-02, +3.762794e-01, +1.436407e-01, +4.341740e-01, +8.753626e-02,
    +1.206723e+00, +4.167565e-02, +2.699763e-02, +4.460426e-02, -1.785336e-01, -1.381946e+00,
    +1.125476e+00, +3.379450e-01, -3.967081e-01, -8.610095e-01, +1.791988e+00, -3.252428e+00,
    -1.391381e-01, -2.993686e-02, +1.475901e+00, -1.693863e+00, -7.249609e-01, -1.120245e-01,
    -1.941198e+00, +2.542674e-01, -1.301074e-01, +2.404422e+00, +1.092078e-01, -3.662846e-02,
    -5.653879e-02, -1.747148e+00, -7.002371e-01, -6.355834e-01, +1.380550e-01, +1.028750e+00,
    -8.286518e-03, +1.736051e+00, -6.394437e-01, +8.347138e-02, +2.893488e-03, +2.600515e-01,
    -3.816916e-01, +4.779264e-01, -1.249347e+00, -7.041677e-01, -9.171308e-02, -7.455603e-01,
    -2.465589e+00, +2.132987e+00, -2.492977e-01, -1.863163e-01, +1.930257e+00, -1.873495e+00,
    -1.747577e+00, -6.010258e-02, +1.916168e+00, +8.150550e-01, -3.081375e-01, -1.169486e+00,
    +6.550370e-03, -3.159251e-01, +7.484894e-02, +5.804454e-01, +1.642717e+00, +1.149419e+00,
    +2.435482e-01, -7.320975e-01, -3.436476e-02, -1.639885e+00, -5.213573e-01, +1.135070e+00,
    -6.439024e-01, +1.072188e+00
  );
  constant drive_b1 : real_vector(0 to 31) := (
    -1.432714e-02, +3.476863e-01, -6.904058e-02, -3.085888e-02, +3.175383e-04, -8.385629e-01,
    -2.872165e-01, +8.997867e-01, -1.570932e-04, -6.843509e-04, -3.892598e+00, +3.373981e+00,
    +1.240659e+00, -1.303960e-03, -4.452320e-01, -3.560996e-01, -1.539408e-03, -1.251718e+00,
    +3.286594e-03, -2.726969e-04, +2.542689e-03, +5.039382e-01, -1.151720e+00, -2.035151e+00,
    -1.156972e-01, +1.592085e+00, -9.823825e-04, -3.090312e-01, -4.420971e-01, -7.355078e-01,
    +4.387922e-03, -4.860355e-01
  );
  constant drive_W2 : real_vector(0 to 31) := (
    -5.164772e-06, +2.085853e-05, -1.954305e-05, +4.445394e-06, +3.708040e-07, -2.328207e-05,
    +2.327790e-05, +2.772959e-05, -1.887142e-07, -8.061472e-07, +4.651488e-05, -3.562954e-05,
    +2.438218e-05, -1.524230e-06, -1.715969e-05, -1.025690e-05, -1.808073e-06, -1.783695e-05,
    +3.738203e-06, -3.453382e-07, +2.888320e-06, -2.096992e-05, -2.967197e-05, -1.814075e-05,
    -3.778286e-06, +2.328448e-05, -1.208320e-06, -2.134779e-05, -1.555621e-05, -9.951732e-06,
    +5.029988e-06, -8.462220e-06
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => +8.654343e-06);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b : integer := 0;
    variable z_a_new, z_b_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 31);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b then
        z_a := z_a_new;
        z_b := z_b_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*vdd_v + drive_W1(32)*V_X_v + drive_W1(64)*A.voltage + drive_W1(96)*B.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*vdd_v + drive_W1(33)*V_X_v + drive_W1(65)*A.voltage + drive_W1(97)*B.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*vdd_v + drive_W1(34)*V_X_v + drive_W1(66)*A.voltage + drive_W1(98)*B.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*vdd_v + drive_W1(35)*V_X_v + drive_W1(67)*A.voltage + drive_W1(99)*B.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*vdd_v + drive_W1(36)*V_X_v + drive_W1(68)*A.voltage + drive_W1(100)*B.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*vdd_v + drive_W1(37)*V_X_v + drive_W1(69)*A.voltage + drive_W1(101)*B.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*vdd_v + drive_W1(38)*V_X_v + drive_W1(70)*A.voltage + drive_W1(102)*B.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*vdd_v + drive_W1(39)*V_X_v + drive_W1(71)*A.voltage + drive_W1(103)*B.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*vdd_v + drive_W1(40)*V_X_v + drive_W1(72)*A.voltage + drive_W1(104)*B.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*vdd_v + drive_W1(41)*V_X_v + drive_W1(73)*A.voltage + drive_W1(105)*B.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*vdd_v + drive_W1(42)*V_X_v + drive_W1(74)*A.voltage + drive_W1(106)*B.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*vdd_v + drive_W1(43)*V_X_v + drive_W1(75)*A.voltage + drive_W1(107)*B.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        z_drive(12) := drive_W1(12)*vdd_v + drive_W1(44)*V_X_v + drive_W1(76)*A.voltage + drive_W1(108)*B.voltage + drive_b1(12);
        if z_drive(12) > 0.0 then h_drive(12) := z_drive(12); else h_drive(12) := 0.01 * z_drive(12); end if;
        z_drive(13) := drive_W1(13)*vdd_v + drive_W1(45)*V_X_v + drive_W1(77)*A.voltage + drive_W1(109)*B.voltage + drive_b1(13);
        if z_drive(13) > 0.0 then h_drive(13) := z_drive(13); else h_drive(13) := 0.01 * z_drive(13); end if;
        z_drive(14) := drive_W1(14)*vdd_v + drive_W1(46)*V_X_v + drive_W1(78)*A.voltage + drive_W1(110)*B.voltage + drive_b1(14);
        if z_drive(14) > 0.0 then h_drive(14) := z_drive(14); else h_drive(14) := 0.01 * z_drive(14); end if;
        z_drive(15) := drive_W1(15)*vdd_v + drive_W1(47)*V_X_v + drive_W1(79)*A.voltage + drive_W1(111)*B.voltage + drive_b1(15);
        if z_drive(15) > 0.0 then h_drive(15) := z_drive(15); else h_drive(15) := 0.01 * z_drive(15); end if;
        z_drive(16) := drive_W1(16)*vdd_v + drive_W1(48)*V_X_v + drive_W1(80)*A.voltage + drive_W1(112)*B.voltage + drive_b1(16);
        if z_drive(16) > 0.0 then h_drive(16) := z_drive(16); else h_drive(16) := 0.01 * z_drive(16); end if;
        z_drive(17) := drive_W1(17)*vdd_v + drive_W1(49)*V_X_v + drive_W1(81)*A.voltage + drive_W1(113)*B.voltage + drive_b1(17);
        if z_drive(17) > 0.0 then h_drive(17) := z_drive(17); else h_drive(17) := 0.01 * z_drive(17); end if;
        z_drive(18) := drive_W1(18)*vdd_v + drive_W1(50)*V_X_v + drive_W1(82)*A.voltage + drive_W1(114)*B.voltage + drive_b1(18);
        if z_drive(18) > 0.0 then h_drive(18) := z_drive(18); else h_drive(18) := 0.01 * z_drive(18); end if;
        z_drive(19) := drive_W1(19)*vdd_v + drive_W1(51)*V_X_v + drive_W1(83)*A.voltage + drive_W1(115)*B.voltage + drive_b1(19);
        if z_drive(19) > 0.0 then h_drive(19) := z_drive(19); else h_drive(19) := 0.01 * z_drive(19); end if;
        z_drive(20) := drive_W1(20)*vdd_v + drive_W1(52)*V_X_v + drive_W1(84)*A.voltage + drive_W1(116)*B.voltage + drive_b1(20);
        if z_drive(20) > 0.0 then h_drive(20) := z_drive(20); else h_drive(20) := 0.01 * z_drive(20); end if;
        z_drive(21) := drive_W1(21)*vdd_v + drive_W1(53)*V_X_v + drive_W1(85)*A.voltage + drive_W1(117)*B.voltage + drive_b1(21);
        if z_drive(21) > 0.0 then h_drive(21) := z_drive(21); else h_drive(21) := 0.01 * z_drive(21); end if;
        z_drive(22) := drive_W1(22)*vdd_v + drive_W1(54)*V_X_v + drive_W1(86)*A.voltage + drive_W1(118)*B.voltage + drive_b1(22);
        if z_drive(22) > 0.0 then h_drive(22) := z_drive(22); else h_drive(22) := 0.01 * z_drive(22); end if;
        z_drive(23) := drive_W1(23)*vdd_v + drive_W1(55)*V_X_v + drive_W1(87)*A.voltage + drive_W1(119)*B.voltage + drive_b1(23);
        if z_drive(23) > 0.0 then h_drive(23) := z_drive(23); else h_drive(23) := 0.01 * z_drive(23); end if;
        z_drive(24) := drive_W1(24)*vdd_v + drive_W1(56)*V_X_v + drive_W1(88)*A.voltage + drive_W1(120)*B.voltage + drive_b1(24);
        if z_drive(24) > 0.0 then h_drive(24) := z_drive(24); else h_drive(24) := 0.01 * z_drive(24); end if;
        z_drive(25) := drive_W1(25)*vdd_v + drive_W1(57)*V_X_v + drive_W1(89)*A.voltage + drive_W1(121)*B.voltage + drive_b1(25);
        if z_drive(25) > 0.0 then h_drive(25) := z_drive(25); else h_drive(25) := 0.01 * z_drive(25); end if;
        z_drive(26) := drive_W1(26)*vdd_v + drive_W1(58)*V_X_v + drive_W1(90)*A.voltage + drive_W1(122)*B.voltage + drive_b1(26);
        if z_drive(26) > 0.0 then h_drive(26) := z_drive(26); else h_drive(26) := 0.01 * z_drive(26); end if;
        z_drive(27) := drive_W1(27)*vdd_v + drive_W1(59)*V_X_v + drive_W1(91)*A.voltage + drive_W1(123)*B.voltage + drive_b1(27);
        if z_drive(27) > 0.0 then h_drive(27) := z_drive(27); else h_drive(27) := 0.01 * z_drive(27); end if;
        z_drive(28) := drive_W1(28)*vdd_v + drive_W1(60)*V_X_v + drive_W1(92)*A.voltage + drive_W1(124)*B.voltage + drive_b1(28);
        if z_drive(28) > 0.0 then h_drive(28) := z_drive(28); else h_drive(28) := 0.01 * z_drive(28); end if;
        z_drive(29) := drive_W1(29)*vdd_v + drive_W1(61)*V_X_v + drive_W1(93)*A.voltage + drive_W1(125)*B.voltage + drive_b1(29);
        if z_drive(29) > 0.0 then h_drive(29) := z_drive(29); else h_drive(29) := 0.01 * z_drive(29); end if;
        z_drive(30) := drive_W1(30)*vdd_v + drive_W1(62)*V_X_v + drive_W1(94)*A.voltage + drive_W1(126)*B.voltage + drive_b1(30);
        if z_drive(30) > 0.0 then h_drive(30) := z_drive(30); else h_drive(30) := 0.01 * z_drive(30); end if;
        z_drive(31) := drive_W1(31)*vdd_v + drive_W1(63)*V_X_v + drive_W1(95)*A.voltage + drive_W1(127)*B.voltage + drive_b1(31);
        if z_drive(31) > 0.0 then h_drive(31) := z_drive(31); else h_drive(31) := 0.01 * z_drive(31); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_W2(12)*h_drive(12) + drive_W2(13)*h_drive(13) + drive_W2(14)*h_drive(14) + drive_W2(15)*h_drive(15) + drive_W2(16)*h_drive(16) + drive_W2(17)*h_drive(17) + drive_W2(18)*h_drive(18) + drive_W2(19)*h_drive(19) + drive_W2(20)*h_drive(20) + drive_W2(21)*h_drive(21) + drive_W2(22)*h_drive(22) + drive_W2(23)*h_drive(23) + drive_W2(24)*h_drive(24) + drive_W2(25)*h_drive(25) + drive_W2(26)*h_drive(26) + drive_W2(27)*h_drive(27) + drive_W2(28)*h_drive(28) + drive_W2(29)*h_drive(29) + drive_W2(30)*h_drive(30) + drive_W2(31)*h_drive(31) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Inverter rule with HOLD zone (completion detection). Only
          -- commit V(Y) to a rail when V(X) is clearly past the PMOS/NMOS
          -- threshold. In between (ACTIVE zone) keep the previous v_y —
          -- this is the event-driven analogue of "the physical inverter
          -- is still mid-transition, so the downstream gate shouldn't
          -- see a new rail yet". Without this the cell snaps to a rail
          -- on every partial input change and the keeper locks it in
          -- prematurely, breaking multi-stage NCL cascades.
          if V_X_v < VTN then
            v_y := vdd_v;
          elsif V_X_v > vdd_v - VTP_ABS then
            v_y := 0.0;
          -- else: hold previous v_y
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
