-- th22_nn.vhd — NN-extracted event-driven VHDL cell model.
-- Generated by /usr/local/src/ldx/asic/chr/extract_cell_va.py (variant=event).
--
-- Uses NVC's logic3da_pkg (sv2vhdl library) for Thevenin-equivalent analog
-- signals. V(output) is a resolved logic3da net — NVC's built-in
-- l3da_resolve composes all drivers (parallel-Thevenin combination) with
-- no matrix solve. Process wakes on input events, runs NN forward pass,
-- emits a single logic3da driver onto the output net. Grounded C and
-- supply-R contributions are separate outputs that aggregator processes
-- sum onto the relevant nets.

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th22_nn is
  port (
    -- Input nets carry Thevenin-equivalent analog signal (voltage+R)
    A : in logic3da;
    B : in logic3da;
    VDD  : in  logic3da;
    VSS  : in  logic3da;
    -- Single Thevenin driver on output net (NVC resolves in parallel).
    Y_drv  : out logic3da;
    -- Grounded-C contribution (resolver just sums these across drivers).
    Y_cap  : out real;
    -- Programmable-R contribution across supply (conductance-form driver).
    VDD_drv : out logic3da
  );
end entity;

architecture nn_event of th22_nn is
  constant R_OUT    : real := 500.0;        -- Thevenin series R (output)
  constant C_OUT    : real := 5.0e-15;      -- grounded output capacitance
  constant G_FLOOR  : real := 1.0e-9;       -- supply conductance floor
  constant R_PWR_HI : real := 1.0e9;        -- supply R ceiling (safety)

  -- SG13G2 PSP103 transistor thresholds. Pull-down (NMOS) begins conducting
  -- at V_gate > Vtn; pull-up (PMOS) at V_gate < VDD - |Vtp|. The NN
  -- evaluates only when an input crosses one of these thresholds.
  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  -- Zone encoding: 0=LOW (< Vtn), 1=ACTIVE (transistors mid-switch), 2=HIGH.
  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant W1 : real_vector(0 to 63) := (+1.640498e-01, +3.061642e-01, +1.751734e-01, -3.893531e-01, +1.947501e-01, +1.338925e-01, -1.544470e-01, +1.835786e-01, +1.102794e-01, +8.662342e-02, +9.385671e-03, +1.632024e-01, -2.205658e-01, +9.338558e-02, -1.850748e-01, +1.806922e-01, +6.517589e-02, -1.303527e-02, -3.479246e-01, -9.660221e-02, -6.871755e-02, -8.166268e-02, +2.496450e-01, +2.763716e-01, -8.126248e-01, -5.689810e-01, -5.117022e-02, -1.271116e-01, +5.091900e-02, +1.494066e-01, +6.516352e-01, -3.349708e-01, -8.207176e-02, +5.127911e-01, +3.003007e-01, +1.189152e-01, -2.310546e-01, -4.948703e-01, +4.527495e-02, +8.375861e-02, -3.687229e-01, -2.036132e-01, -2.235045e-02, -2.830516e-01, -4.386064e-02, -5.919944e-02, +3.056404e-02, -1.528756e-01, +3.524029e-01, +5.489458e-01, -1.427174e-01, -2.420502e-01, +1.452122e-01, -1.496216e-01, +2.827946e-01, -3.599236e-01, +2.765895e-01, -1.083739e-02, -3.720342e-01, -9.601503e-02, +1.750626e-02, +4.508334e-01, -3.427931e-01, -3.294455e-01);
  constant W1_COLS : integer := 16;
  constant b1 : real_vector(0 to 15) := (+2.416934e-02, -2.008600e-02, +1.526349e-03, -3.784837e-02, -6.107123e-02, -9.211168e-05, -1.476997e-02, +2.061991e-02, -9.322187e-05, +2.550152e-04, -1.396455e-04, +6.521174e-05, -1.077879e-02, -5.106214e-02, +4.133415e-04, -2.794488e-03);
  constant W2 : real_vector(0 to 31) := (+3.303127e-01, -1.459713e-04, +4.301131e-01, +1.228790e-04, -6.315818e-01, -4.522785e-05, +3.256028e-01, -1.156852e-04, -1.832183e-01, +2.271983e-04, +7.592735e-02, +2.688455e-04, +1.078891e-01, -3.411710e-04, -1.836477e-01, -7.914425e-05, +2.345050e-01, +5.591026e-05, -4.899084e-01, -3.602060e-04, +2.615113e-01, +2.036651e-04, -1.920434e-01, -6.302004e-07, +1.242882e-01, +1.473149e-04, +5.373056e-01, +1.118917e-04, -2.453381e-01, +1.116484e-04, +3.004492e-01, -6.824787e-04);
  constant W2_COLS : integer := 2;
  constant b2 : real_vector(0 to 1) := (-3.391437e-02, -2.474572e-05);

  signal v_pred : real := 0.0;
  signal g_pred : real := G_FLOOR;
begin
  -- NN forward pass — event-driven wake-up on rail departure. The process
  -- holds state in `y_prev` across wake-ups and evaluates only when one of
  -- the inputs enters / leaves its ACTIVE zone. Matches the hybrid_evt
  -- cell; drastically reduces simulator work on long NCL hold phases.
  nn_proc : process
    variable y_prev : real := 0.0;
    variable z_a, z_b : integer := 0;
    variable z_a_new, z_b_new : integer;
    variable z1, h : real_vector(0 to 15);
    variable y     : real_vector(0 to 1);
    variable vp, gp, vdd_now : real;
  begin
    -- (no rate features; state via y_prev only)

    -- Prime the driver at t=0 so downstream nets see a defined value
    -- before the first input edge.
    v_pred <= 0.0;
    g_pred <= G_FLOOR;

    loop
      wait on A, B, VDD;

      vdd_now := VDD.voltage;
    z_a_new := zone(A.voltage, vdd_now);
    z_b_new := zone(B.voltage, vdd_now);

      -- Skip NN forward pass if no input's zone changed — the keeper /
      -- hysteresis built into the NN's fixed point is already at its
      -- steady value for the current zone configuration.
      if z_a_new /= z_a or z_b_new /= z_b then
      z_a := z_a_new;
      z_b := z_b_new;

        -- Fixed-point iteration of the NN forward pass with V(out) self-
        -- feedback. Inside one wake-up we need to converge y_prev because
        -- the process loop is what schedules the next wait — no implicit
        -- re-trigger like the old `process(..., y_drv)` form.
        for iter in 0 to 31 loop
          -- Hidden layer (leaky-ReLU)
          z1(0) := W1(0)*A.voltage + W1(16)*B.voltage + W1(32)*VDD.voltage + W1(48)*y_prev + b1(0);
          if z1(0) > 0.0 then h(0) := z1(0); else h(0) := 0.0100 * z1(0); end if;
          z1(1) := W1(1)*A.voltage + W1(17)*B.voltage + W1(33)*VDD.voltage + W1(49)*y_prev + b1(1);
          if z1(1) > 0.0 then h(1) := z1(1); else h(1) := 0.0100 * z1(1); end if;
          z1(2) := W1(2)*A.voltage + W1(18)*B.voltage + W1(34)*VDD.voltage + W1(50)*y_prev + b1(2);
          if z1(2) > 0.0 then h(2) := z1(2); else h(2) := 0.0100 * z1(2); end if;
          z1(3) := W1(3)*A.voltage + W1(19)*B.voltage + W1(35)*VDD.voltage + W1(51)*y_prev + b1(3);
          if z1(3) > 0.0 then h(3) := z1(3); else h(3) := 0.0100 * z1(3); end if;
          z1(4) := W1(4)*A.voltage + W1(20)*B.voltage + W1(36)*VDD.voltage + W1(52)*y_prev + b1(4);
          if z1(4) > 0.0 then h(4) := z1(4); else h(4) := 0.0100 * z1(4); end if;
          z1(5) := W1(5)*A.voltage + W1(21)*B.voltage + W1(37)*VDD.voltage + W1(53)*y_prev + b1(5);
          if z1(5) > 0.0 then h(5) := z1(5); else h(5) := 0.0100 * z1(5); end if;
          z1(6) := W1(6)*A.voltage + W1(22)*B.voltage + W1(38)*VDD.voltage + W1(54)*y_prev + b1(6);
          if z1(6) > 0.0 then h(6) := z1(6); else h(6) := 0.0100 * z1(6); end if;
          z1(7) := W1(7)*A.voltage + W1(23)*B.voltage + W1(39)*VDD.voltage + W1(55)*y_prev + b1(7);
          if z1(7) > 0.0 then h(7) := z1(7); else h(7) := 0.0100 * z1(7); end if;
          z1(8) := W1(8)*A.voltage + W1(24)*B.voltage + W1(40)*VDD.voltage + W1(56)*y_prev + b1(8);
          if z1(8) > 0.0 then h(8) := z1(8); else h(8) := 0.0100 * z1(8); end if;
          z1(9) := W1(9)*A.voltage + W1(25)*B.voltage + W1(41)*VDD.voltage + W1(57)*y_prev + b1(9);
          if z1(9) > 0.0 then h(9) := z1(9); else h(9) := 0.0100 * z1(9); end if;
          z1(10) := W1(10)*A.voltage + W1(26)*B.voltage + W1(42)*VDD.voltage + W1(58)*y_prev + b1(10);
          if z1(10) > 0.0 then h(10) := z1(10); else h(10) := 0.0100 * z1(10); end if;
          z1(11) := W1(11)*A.voltage + W1(27)*B.voltage + W1(43)*VDD.voltage + W1(59)*y_prev + b1(11);
          if z1(11) > 0.0 then h(11) := z1(11); else h(11) := 0.0100 * z1(11); end if;
          z1(12) := W1(12)*A.voltage + W1(28)*B.voltage + W1(44)*VDD.voltage + W1(60)*y_prev + b1(12);
          if z1(12) > 0.0 then h(12) := z1(12); else h(12) := 0.0100 * z1(12); end if;
          z1(13) := W1(13)*A.voltage + W1(29)*B.voltage + W1(45)*VDD.voltage + W1(61)*y_prev + b1(13);
          if z1(13) > 0.0 then h(13) := z1(13); else h(13) := 0.0100 * z1(13); end if;
          z1(14) := W1(14)*A.voltage + W1(30)*B.voltage + W1(46)*VDD.voltage + W1(62)*y_prev + b1(14);
          if z1(14) > 0.0 then h(14) := z1(14); else h(14) := 0.0100 * z1(14); end if;
          z1(15) := W1(15)*A.voltage + W1(31)*B.voltage + W1(47)*VDD.voltage + W1(63)*y_prev + b1(15);
          if z1(15) > 0.0 then h(15) := z1(15); else h(15) := 0.0100 * z1(15); end if;
          -- Output layer
          y(0) := W2(0)*h(0) + W2(2)*h(1) + W2(4)*h(2) + W2(6)*h(3) + W2(8)*h(4) + W2(10)*h(5) + W2(12)*h(6) + W2(14)*h(7) + W2(16)*h(8) + W2(18)*h(9) + W2(20)*h(10) + W2(22)*h(11) + W2(24)*h(12) + W2(26)*h(13) + W2(28)*h(14) + W2(30)*h(15) + b2(0);
          y(1) := W2(1)*h(0) + W2(3)*h(1) + W2(5)*h(2) + W2(7)*h(3) + W2(9)*h(4) + W2(11)*h(5) + W2(13)*h(6) + W2(15)*h(7) + W2(17)*h(8) + W2(19)*h(9) + W2(21)*h(10) + W2(23)*h(11) + W2(25)*h(12) + W2(27)*h(13) + W2(29)*h(14) + W2(31)*h(15) + b2(1);

          vp := y(0);
          gp := G_FLOOR;
          if y(1) > 0.0 then gp := gp + y(1); end if;
          if vp > vdd_now    then vp := vdd_now;      end if;
          if vp < VSS.voltage then vp := VSS.voltage; end if;

          exit when abs(vp - y_prev) < 1.0e-4;
          y_prev := vp;
        end loop;

        v_pred <= vp;
        g_pred <= gp;
        y_prev := vp;
      end if;
    end loop;
  end process;

  -- Emit Thevenin driver on output net Y: voltage = v_pred,
  -- source resistance R_OUT. NVC's l3da_resolve composes this with any
  -- other drivers on the same resolved net.
  Y_drv <= (voltage => v_pred, resistance => R_OUT,
                     flags => AFL_KNOWN);

  -- Grounded-C contribution (resolver sums these across drivers).
  Y_cap <= C_OUT;

  -- Programmable supply R: emit on VDD_drv as a logic3da driver between
  -- VDD and VSS (equivalent to a resistor of value 1/g_pred).
  VDD_drv <= (voltage => VSS.voltage, resistance => 1.0 / g_pred,
              flags => AFL_KNOWN);

end architecture;
