-- th23_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th23_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    C       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th23_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 47) := (
    +2.762394e-01, -7.211151e-01, -3.932240e-01, +3.300053e-01, -1.928970e-01, -6.524770e+00,
    +3.904354e-02, +3.952615e+00, +1.992357e-01, -3.451261e-01, +2.321673e-01, +3.961272e+00,
    +4.261350e-01, +6.040443e-01, -1.004779e+00, +3.494826e+00, -4.028122e-01, +1.503106e+00,
    -5.699001e-01, -1.237045e+00, -3.890328e+00, -8.624321e-01, -3.781054e+00, -1.232987e+00,
    +3.079925e+00, +1.163194e-01, -9.213453e-01, +1.425097e+00, +6.046696e-02, +2.123331e+00,
    -4.582976e-01, -1.059063e+00, +8.020587e-02, -7.855496e-01, +6.614372e-01, -1.718477e-02,
    +3.432824e+00, +4.542546e-01, -9.724798e-01, +1.424574e+00, +8.049796e-02, +2.183111e+00,
    -3.668163e-01, -1.062032e+00, +8.465471e-02, -8.340674e-01, +6.575138e-01, +7.873333e-02
  );
  constant drive_b1 : real_vector(0 to 11) := (
    -6.648909e+00, +8.641857e-01, +9.042941e-01, -5.648780e+00, -2.913758e-02, -4.865928e+00,
    -1.460037e-02, +1.769839e+00, +1.924267e+00, +7.757959e-01, +2.130411e+00, +1.784088e+00
  );
  constant drive_W2 : real_vector(0 to 11) := (
    -7.740429e-05, +1.229835e-05, +1.793933e-05, -6.270400e-05, +1.684781e-06, +8.756974e-05,
    -5.389412e-07, +4.312626e-05, -4.239236e-05, +1.581521e-05, +4.344190e-05, -4.116563e-05
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => -2.995341e-06);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b, z_c : integer := 0;
    variable z_a_new, z_b_new, z_c_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 11);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, C, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);
      z_c_new := zone(C.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b or z_c_new /= z_c then
        z_a := z_a_new;
        z_b := z_b_new;
        z_c := z_c_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*V_X_v + drive_W1(12)*A.voltage + drive_W1(24)*B.voltage + drive_W1(36)*C.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*V_X_v + drive_W1(13)*A.voltage + drive_W1(25)*B.voltage + drive_W1(37)*C.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*V_X_v + drive_W1(14)*A.voltage + drive_W1(26)*B.voltage + drive_W1(38)*C.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*V_X_v + drive_W1(15)*A.voltage + drive_W1(27)*B.voltage + drive_W1(39)*C.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*V_X_v + drive_W1(16)*A.voltage + drive_W1(28)*B.voltage + drive_W1(40)*C.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*V_X_v + drive_W1(17)*A.voltage + drive_W1(29)*B.voltage + drive_W1(41)*C.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*V_X_v + drive_W1(18)*A.voltage + drive_W1(30)*B.voltage + drive_W1(42)*C.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*V_X_v + drive_W1(19)*A.voltage + drive_W1(31)*B.voltage + drive_W1(43)*C.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*V_X_v + drive_W1(20)*A.voltage + drive_W1(32)*B.voltage + drive_W1(44)*C.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*V_X_v + drive_W1(21)*A.voltage + drive_W1(33)*B.voltage + drive_W1(45)*C.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*V_X_v + drive_W1(22)*A.voltage + drive_W1(34)*B.voltage + drive_W1(46)*C.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*V_X_v + drive_W1(23)*A.voltage + drive_W1(35)*B.voltage + drive_W1(47)*C.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Digital inverter: V(Y) = NOT V(X) (same rule as hybrid_evt).
          if V_X_v > VTN then
            v_y := 0.0;
          else
            v_y := vdd_v;
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
