-- th23_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th23_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    C       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th23_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 199) := (
    -9.949869e-01, +5.527589e-01, +2.101631e-01, -2.819139e-01, -4.604688e-01, -3.223428e-01,
    -3.147813e-01, +7.751463e-02, -2.768603e-01, -1.613035e-01, +7.438530e-02, +6.463667e-01,
    -4.562820e-02, -1.187063e-01, -5.009783e-02, -3.251956e-01, +1.908757e-01, -1.337306e+00,
    -9.565911e-01, -3.637001e-01, -5.551374e-01, -5.553950e-02, +3.980582e-02, +9.603628e-03,
    +2.264185e-01, -6.280342e-02, +2.873635e-01, +4.495178e-02, -1.061221e-01, -2.203240e-01,
    -6.143317e-01, +1.107677e-01, -3.426884e-01, -2.484420e-01, +4.127971e-01, +1.411892e-01,
    -4.084308e-02, -2.644644e-03, +8.503257e-02, -1.126753e-01, +2.543186e+00, -3.573771e+00,
    -5.478896e+00, +1.692154e-02, +7.421980e+00, -4.745313e-01, +5.997204e+00, +6.736191e-01,
    -2.433196e-01, +3.920590e+00, +5.767687e+00, -4.741040e+00, +4.861661e+00, +7.368277e-01,
    -1.048133e+00, +2.582595e+00, -2.877615e+00, +1.907718e+00, +2.873580e+00, -1.921190e-01,
    +5.536454e-02, -1.322168e-01, -1.728984e+00, -4.491996e+00, +6.277734e-01, -6.159666e-02,
    +1.096913e+00, +1.104758e+00, -4.511016e+00, -5.229085e-01, -3.573692e-01, -1.240369e+00,
    -1.311572e-01, -3.154053e-02, +4.240747e+00, -1.156247e+00, -4.002478e+00, -4.310670e+00,
    +1.954701e+00, -3.871008e-01, -5.344721e-01, -1.078655e+00, +1.527606e+00, -3.494405e-02,
    +4.994217e-01, -3.333775e-01, +6.299849e-01, +3.404252e+00, +2.022722e-01, +1.440811e+00,
    +1.205680e+00, +2.510898e+00, -1.805504e+00, +8.390338e+00, +5.854964e+00, +1.033356e+00,
    -3.215835e+00, +6.923367e-02, -1.488416e+00, -6.099654e-01, -9.095963e-02, -2.696748e-01,
    +1.821146e-01, +4.779130e+00, -9.994321e-01, -1.866785e-01, +1.522812e-01, +2.779606e+00,
    +3.715725e+00, +1.277103e+00, +7.962185e+00, +1.186183e+00, -3.114880e-01, -2.340519e-02,
    +5.569381e-01, +2.641088e+00, -1.257088e+00, +5.384275e-01, +8.051421e-01, +3.383177e+00,
    +4.203427e-01, -3.089548e-01, +2.636286e+00, -6.121806e-01, -2.697889e-01, +8.836225e-02,
    -3.429752e+00, +3.503542e+00, -5.199554e-01, +1.779713e+00, -5.456121e+00, +2.428684e+00,
    -6.088466e-01, -1.151963e-01, -3.248600e-01, -2.854587e+00, -1.430903e-01, +4.565993e+00,
    -1.222823e+00, -2.743917e-01, +3.241800e-01, -1.510512e-01, +4.019818e+00, +5.667170e-02,
    -5.571636e-01, -3.890665e-01, +3.496960e+00, +4.511696e-01, +2.986381e-01, +7.117939e-01,
    -7.213929e-01, -4.275107e+00, -1.769187e-01, -2.538491e-03, +4.334411e-02, +1.618627e-01,
    -4.890864e-01, +6.065402e-01, +9.484426e-01, +1.259404e+00, -2.327272e+00, +6.002243e-01,
    +1.873512e+00, -4.512042e-01, -1.984097e+00, -2.143786e-01, -2.059714e+00, +3.933796e-01,
    -7.658881e-02, -1.946920e-01, +1.136067e+00, +2.215542e+00, -2.550592e+00, -6.423535e-01,
    -4.043085e+00, +2.531305e+00, +2.759420e+00, -3.997904e+00, -1.503242e+00, +1.281933e-02,
    -1.305304e-01, -1.375249e-01, +3.690283e+00, +3.482696e-01, -4.622567e+00, -1.411898e-04,
    +4.297861e+00, +2.087179e+00, +2.174913e+00, -6.144720e+00, -1.272615e+00, +7.733670e-01,
    +2.184623e-01, -4.803502e-02, -3.051568e+00, +2.437105e+00, +3.973453e+00, +3.284583e+00,
    -1.611481e+00, +3.428304e+00
  );
  constant drive_b1 : real_vector(0 to 39) := (
    -1.898369e-01, +2.604088e+00, -5.814870e+00, -9.434528e-03, -1.194626e+00, -1.612020e-02,
    +3.557624e-01, -9.013025e+00, -1.146243e-01, -3.240333e+00, +1.554253e+00, -9.445333e+00,
    +2.129463e-01, -6.094042e+00, +5.168799e-01, +8.115369e-01, -7.990292e-01, -8.189961e-01,
    -9.267375e-01, +1.520666e-02, -3.116006e-03, +9.829564e-03, -6.959101e+00, -3.351030e+00,
    +1.265380e+00, -4.314140e-03, -1.055343e+01, -7.063767e+00, -2.931357e+00, +2.540589e+00,
    -4.543873e+00, +1.122926e+00, -4.853925e-02, -3.738412e-03, +1.078351e+00, -4.919925e+00,
    -1.014187e+00, -3.917251e+00, +7.534626e-01, -9.283760e+00
  );
  constant drive_W2 : real_vector(0 to 39) := (
    -1.816060e-05, +2.036463e-05, +3.652215e-05, +3.254997e-06, +2.067778e-05, +4.787208e-06,
    -1.758677e-05, -2.241758e-05, +2.658119e-06, -1.634536e-05, +2.376888e-05, +6.655626e-05,
    -1.687952e-05, -2.413220e-05, +1.724928e-05, -1.602865e-05, -3.678449e-05, +1.846540e-05,
    -3.799267e-05, -4.174182e-06, -2.787670e-07, -2.705519e-06, -1.761902e-05, +2.878302e-05,
    +4.290626e-05, +1.427600e-06, -2.385898e-05, -1.854767e-05, -2.229369e-05, -3.456210e-05,
    +2.163057e-05, -2.572514e-05, +1.036148e-06, +1.179940e-06, +1.534925e-05, -1.387887e-05,
    +2.572387e-05, +3.761151e-05, -1.262112e-05, -2.065131e-05
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => -3.467286e-05);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b, z_c : integer := 0;
    variable z_a_new, z_b_new, z_c_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 39);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, C, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);
      z_c_new := zone(C.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b or z_c_new /= z_c then
        z_a := z_a_new;
        z_b := z_b_new;
        z_c := z_c_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*vdd_v + drive_W1(40)*V_X_v + drive_W1(80)*A.voltage + drive_W1(120)*B.voltage + drive_W1(160)*C.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*vdd_v + drive_W1(41)*V_X_v + drive_W1(81)*A.voltage + drive_W1(121)*B.voltage + drive_W1(161)*C.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*vdd_v + drive_W1(42)*V_X_v + drive_W1(82)*A.voltage + drive_W1(122)*B.voltage + drive_W1(162)*C.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*vdd_v + drive_W1(43)*V_X_v + drive_W1(83)*A.voltage + drive_W1(123)*B.voltage + drive_W1(163)*C.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*vdd_v + drive_W1(44)*V_X_v + drive_W1(84)*A.voltage + drive_W1(124)*B.voltage + drive_W1(164)*C.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*vdd_v + drive_W1(45)*V_X_v + drive_W1(85)*A.voltage + drive_W1(125)*B.voltage + drive_W1(165)*C.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*vdd_v + drive_W1(46)*V_X_v + drive_W1(86)*A.voltage + drive_W1(126)*B.voltage + drive_W1(166)*C.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*vdd_v + drive_W1(47)*V_X_v + drive_W1(87)*A.voltage + drive_W1(127)*B.voltage + drive_W1(167)*C.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*vdd_v + drive_W1(48)*V_X_v + drive_W1(88)*A.voltage + drive_W1(128)*B.voltage + drive_W1(168)*C.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*vdd_v + drive_W1(49)*V_X_v + drive_W1(89)*A.voltage + drive_W1(129)*B.voltage + drive_W1(169)*C.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*vdd_v + drive_W1(50)*V_X_v + drive_W1(90)*A.voltage + drive_W1(130)*B.voltage + drive_W1(170)*C.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*vdd_v + drive_W1(51)*V_X_v + drive_W1(91)*A.voltage + drive_W1(131)*B.voltage + drive_W1(171)*C.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        z_drive(12) := drive_W1(12)*vdd_v + drive_W1(52)*V_X_v + drive_W1(92)*A.voltage + drive_W1(132)*B.voltage + drive_W1(172)*C.voltage + drive_b1(12);
        if z_drive(12) > 0.0 then h_drive(12) := z_drive(12); else h_drive(12) := 0.01 * z_drive(12); end if;
        z_drive(13) := drive_W1(13)*vdd_v + drive_W1(53)*V_X_v + drive_W1(93)*A.voltage + drive_W1(133)*B.voltage + drive_W1(173)*C.voltage + drive_b1(13);
        if z_drive(13) > 0.0 then h_drive(13) := z_drive(13); else h_drive(13) := 0.01 * z_drive(13); end if;
        z_drive(14) := drive_W1(14)*vdd_v + drive_W1(54)*V_X_v + drive_W1(94)*A.voltage + drive_W1(134)*B.voltage + drive_W1(174)*C.voltage + drive_b1(14);
        if z_drive(14) > 0.0 then h_drive(14) := z_drive(14); else h_drive(14) := 0.01 * z_drive(14); end if;
        z_drive(15) := drive_W1(15)*vdd_v + drive_W1(55)*V_X_v + drive_W1(95)*A.voltage + drive_W1(135)*B.voltage + drive_W1(175)*C.voltage + drive_b1(15);
        if z_drive(15) > 0.0 then h_drive(15) := z_drive(15); else h_drive(15) := 0.01 * z_drive(15); end if;
        z_drive(16) := drive_W1(16)*vdd_v + drive_W1(56)*V_X_v + drive_W1(96)*A.voltage + drive_W1(136)*B.voltage + drive_W1(176)*C.voltage + drive_b1(16);
        if z_drive(16) > 0.0 then h_drive(16) := z_drive(16); else h_drive(16) := 0.01 * z_drive(16); end if;
        z_drive(17) := drive_W1(17)*vdd_v + drive_W1(57)*V_X_v + drive_W1(97)*A.voltage + drive_W1(137)*B.voltage + drive_W1(177)*C.voltage + drive_b1(17);
        if z_drive(17) > 0.0 then h_drive(17) := z_drive(17); else h_drive(17) := 0.01 * z_drive(17); end if;
        z_drive(18) := drive_W1(18)*vdd_v + drive_W1(58)*V_X_v + drive_W1(98)*A.voltage + drive_W1(138)*B.voltage + drive_W1(178)*C.voltage + drive_b1(18);
        if z_drive(18) > 0.0 then h_drive(18) := z_drive(18); else h_drive(18) := 0.01 * z_drive(18); end if;
        z_drive(19) := drive_W1(19)*vdd_v + drive_W1(59)*V_X_v + drive_W1(99)*A.voltage + drive_W1(139)*B.voltage + drive_W1(179)*C.voltage + drive_b1(19);
        if z_drive(19) > 0.0 then h_drive(19) := z_drive(19); else h_drive(19) := 0.01 * z_drive(19); end if;
        z_drive(20) := drive_W1(20)*vdd_v + drive_W1(60)*V_X_v + drive_W1(100)*A.voltage + drive_W1(140)*B.voltage + drive_W1(180)*C.voltage + drive_b1(20);
        if z_drive(20) > 0.0 then h_drive(20) := z_drive(20); else h_drive(20) := 0.01 * z_drive(20); end if;
        z_drive(21) := drive_W1(21)*vdd_v + drive_W1(61)*V_X_v + drive_W1(101)*A.voltage + drive_W1(141)*B.voltage + drive_W1(181)*C.voltage + drive_b1(21);
        if z_drive(21) > 0.0 then h_drive(21) := z_drive(21); else h_drive(21) := 0.01 * z_drive(21); end if;
        z_drive(22) := drive_W1(22)*vdd_v + drive_W1(62)*V_X_v + drive_W1(102)*A.voltage + drive_W1(142)*B.voltage + drive_W1(182)*C.voltage + drive_b1(22);
        if z_drive(22) > 0.0 then h_drive(22) := z_drive(22); else h_drive(22) := 0.01 * z_drive(22); end if;
        z_drive(23) := drive_W1(23)*vdd_v + drive_W1(63)*V_X_v + drive_W1(103)*A.voltage + drive_W1(143)*B.voltage + drive_W1(183)*C.voltage + drive_b1(23);
        if z_drive(23) > 0.0 then h_drive(23) := z_drive(23); else h_drive(23) := 0.01 * z_drive(23); end if;
        z_drive(24) := drive_W1(24)*vdd_v + drive_W1(64)*V_X_v + drive_W1(104)*A.voltage + drive_W1(144)*B.voltage + drive_W1(184)*C.voltage + drive_b1(24);
        if z_drive(24) > 0.0 then h_drive(24) := z_drive(24); else h_drive(24) := 0.01 * z_drive(24); end if;
        z_drive(25) := drive_W1(25)*vdd_v + drive_W1(65)*V_X_v + drive_W1(105)*A.voltage + drive_W1(145)*B.voltage + drive_W1(185)*C.voltage + drive_b1(25);
        if z_drive(25) > 0.0 then h_drive(25) := z_drive(25); else h_drive(25) := 0.01 * z_drive(25); end if;
        z_drive(26) := drive_W1(26)*vdd_v + drive_W1(66)*V_X_v + drive_W1(106)*A.voltage + drive_W1(146)*B.voltage + drive_W1(186)*C.voltage + drive_b1(26);
        if z_drive(26) > 0.0 then h_drive(26) := z_drive(26); else h_drive(26) := 0.01 * z_drive(26); end if;
        z_drive(27) := drive_W1(27)*vdd_v + drive_W1(67)*V_X_v + drive_W1(107)*A.voltage + drive_W1(147)*B.voltage + drive_W1(187)*C.voltage + drive_b1(27);
        if z_drive(27) > 0.0 then h_drive(27) := z_drive(27); else h_drive(27) := 0.01 * z_drive(27); end if;
        z_drive(28) := drive_W1(28)*vdd_v + drive_W1(68)*V_X_v + drive_W1(108)*A.voltage + drive_W1(148)*B.voltage + drive_W1(188)*C.voltage + drive_b1(28);
        if z_drive(28) > 0.0 then h_drive(28) := z_drive(28); else h_drive(28) := 0.01 * z_drive(28); end if;
        z_drive(29) := drive_W1(29)*vdd_v + drive_W1(69)*V_X_v + drive_W1(109)*A.voltage + drive_W1(149)*B.voltage + drive_W1(189)*C.voltage + drive_b1(29);
        if z_drive(29) > 0.0 then h_drive(29) := z_drive(29); else h_drive(29) := 0.01 * z_drive(29); end if;
        z_drive(30) := drive_W1(30)*vdd_v + drive_W1(70)*V_X_v + drive_W1(110)*A.voltage + drive_W1(150)*B.voltage + drive_W1(190)*C.voltage + drive_b1(30);
        if z_drive(30) > 0.0 then h_drive(30) := z_drive(30); else h_drive(30) := 0.01 * z_drive(30); end if;
        z_drive(31) := drive_W1(31)*vdd_v + drive_W1(71)*V_X_v + drive_W1(111)*A.voltage + drive_W1(151)*B.voltage + drive_W1(191)*C.voltage + drive_b1(31);
        if z_drive(31) > 0.0 then h_drive(31) := z_drive(31); else h_drive(31) := 0.01 * z_drive(31); end if;
        z_drive(32) := drive_W1(32)*vdd_v + drive_W1(72)*V_X_v + drive_W1(112)*A.voltage + drive_W1(152)*B.voltage + drive_W1(192)*C.voltage + drive_b1(32);
        if z_drive(32) > 0.0 then h_drive(32) := z_drive(32); else h_drive(32) := 0.01 * z_drive(32); end if;
        z_drive(33) := drive_W1(33)*vdd_v + drive_W1(73)*V_X_v + drive_W1(113)*A.voltage + drive_W1(153)*B.voltage + drive_W1(193)*C.voltage + drive_b1(33);
        if z_drive(33) > 0.0 then h_drive(33) := z_drive(33); else h_drive(33) := 0.01 * z_drive(33); end if;
        z_drive(34) := drive_W1(34)*vdd_v + drive_W1(74)*V_X_v + drive_W1(114)*A.voltage + drive_W1(154)*B.voltage + drive_W1(194)*C.voltage + drive_b1(34);
        if z_drive(34) > 0.0 then h_drive(34) := z_drive(34); else h_drive(34) := 0.01 * z_drive(34); end if;
        z_drive(35) := drive_W1(35)*vdd_v + drive_W1(75)*V_X_v + drive_W1(115)*A.voltage + drive_W1(155)*B.voltage + drive_W1(195)*C.voltage + drive_b1(35);
        if z_drive(35) > 0.0 then h_drive(35) := z_drive(35); else h_drive(35) := 0.01 * z_drive(35); end if;
        z_drive(36) := drive_W1(36)*vdd_v + drive_W1(76)*V_X_v + drive_W1(116)*A.voltage + drive_W1(156)*B.voltage + drive_W1(196)*C.voltage + drive_b1(36);
        if z_drive(36) > 0.0 then h_drive(36) := z_drive(36); else h_drive(36) := 0.01 * z_drive(36); end if;
        z_drive(37) := drive_W1(37)*vdd_v + drive_W1(77)*V_X_v + drive_W1(117)*A.voltage + drive_W1(157)*B.voltage + drive_W1(197)*C.voltage + drive_b1(37);
        if z_drive(37) > 0.0 then h_drive(37) := z_drive(37); else h_drive(37) := 0.01 * z_drive(37); end if;
        z_drive(38) := drive_W1(38)*vdd_v + drive_W1(78)*V_X_v + drive_W1(118)*A.voltage + drive_W1(158)*B.voltage + drive_W1(198)*C.voltage + drive_b1(38);
        if z_drive(38) > 0.0 then h_drive(38) := z_drive(38); else h_drive(38) := 0.01 * z_drive(38); end if;
        z_drive(39) := drive_W1(39)*vdd_v + drive_W1(79)*V_X_v + drive_W1(119)*A.voltage + drive_W1(159)*B.voltage + drive_W1(199)*C.voltage + drive_b1(39);
        if z_drive(39) > 0.0 then h_drive(39) := z_drive(39); else h_drive(39) := 0.01 * z_drive(39); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_W2(12)*h_drive(12) + drive_W2(13)*h_drive(13) + drive_W2(14)*h_drive(14) + drive_W2(15)*h_drive(15) + drive_W2(16)*h_drive(16) + drive_W2(17)*h_drive(17) + drive_W2(18)*h_drive(18) + drive_W2(19)*h_drive(19) + drive_W2(20)*h_drive(20) + drive_W2(21)*h_drive(21) + drive_W2(22)*h_drive(22) + drive_W2(23)*h_drive(23) + drive_W2(24)*h_drive(24) + drive_W2(25)*h_drive(25) + drive_W2(26)*h_drive(26) + drive_W2(27)*h_drive(27) + drive_W2(28)*h_drive(28) + drive_W2(29)*h_drive(29) + drive_W2(30)*h_drive(30) + drive_W2(31)*h_drive(31) + drive_W2(32)*h_drive(32) + drive_W2(33)*h_drive(33) + drive_W2(34)*h_drive(34) + drive_W2(35)*h_drive(35) + drive_W2(36)*h_drive(36) + drive_W2(37)*h_drive(37) + drive_W2(38)*h_drive(38) + drive_W2(39)*h_drive(39) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Inverter rule with HOLD zone (completion detection). Only
          -- commit V(Y) to a rail when V(X) is clearly past the PMOS/NMOS
          -- threshold. In between (ACTIVE zone) keep the previous v_y —
          -- this is the event-driven analogue of "the physical inverter
          -- is still mid-transition, so the downstream gate shouldn't
          -- see a new rail yet". Without this the cell snaps to a rail
          -- on every partial input change and the keeper locks it in
          -- prematurely, breaking multi-stage NCL cascades.
          if V_X_v < VTN then
            v_y := vdd_v;
          elsif V_X_v > vdd_v - VTP_ABS then
            v_y := 0.0;
          -- else: hold previous v_y
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
