-- th34w2_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th34w2_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    C       : in  logic3da;
    D       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th34w2_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 69) := (
    -6.825026e-02, +3.089031e-01, +5.869116e-01, -2.663698e-01, +7.152850e-01, -2.973148e-01,
    +2.932809e-01, +2.621355e-01, +2.925619e-01, -7.204468e+00, +2.195753e-01, +3.826953e-01,
    +1.187369e-02, +1.125153e-01, -6.680143e-02, +3.751180e+00, -3.723220e+00, -1.368538e-01,
    -7.069076e+00, -4.075400e-01, -5.246321e+00, +3.611638e+00, +1.079033e-01, +2.834382e+00,
    +4.256593e+00, -2.277773e+00, -7.672078e-01, +5.421277e-01, -1.224044e+00, +2.708107e+00,
    +3.104729e-02, -1.433673e-01, +1.002649e-01, -2.609934e-01, -5.831403e-01, +6.681573e-02,
    +1.608706e+00, +1.074748e+00, +1.646100e-02, +1.873804e+00, -5.766428e-03, -1.781834e+00,
    -8.484722e-01, -1.367182e-01, +4.938214e-02, -4.639001e-01, +8.730197e-02, -6.459936e-02,
    -5.842256e-01, +2.709819e+00, +1.707530e+00, +1.088692e+00, +6.864964e-03, +1.706016e+00,
    -5.910040e-02, +5.521034e-01, -1.139117e+00, +6.539154e-02, +2.007239e+00, -2.024875e-01,
    +3.490922e-01, -1.450009e-01, -7.883966e-01, +1.211195e-01, +1.623433e+00, +1.011574e+00,
    +2.520046e+00, +2.932109e-01, -4.021773e-01, -4.589304e-01
  );
  constant drive_b1 : real_vector(0 to 13) := (
    +1.155125e+00, -6.499299e+00, +1.947861e+00, -3.136263e-06, +5.415677e+00, +8.074439e-02,
    +4.927222e+00, -6.538529e+00, -4.969136e+00, -4.255280e+00, -6.897786e+00, +5.578793e-01,
    -1.915834e-02, -2.688053e-01
  );
  constant drive_W2 : real_vector(0 to 13) := (
    +2.150656e-05, -6.582626e-05, -3.867112e-05, +4.769204e-08, +8.003983e-05, +2.818656e-06,
    -6.848108e-05, -6.887003e-05, -5.434844e-05, +8.161291e-05, -7.418363e-05, -2.748762e-05,
    +1.804735e-06, -1.907467e-05
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => -5.390527e-06);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b, z_c, z_d : integer := 0;
    variable z_a_new, z_b_new, z_c_new, z_d_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 13);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, C, D, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);
      z_c_new := zone(C.voltage, vdd_v);
      z_d_new := zone(D.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b or z_c_new /= z_c or z_d_new /= z_d then
        z_a := z_a_new;
        z_b := z_b_new;
        z_c := z_c_new;
        z_d := z_d_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*V_X_v + drive_W1(14)*A.voltage + drive_W1(28)*B.voltage + drive_W1(42)*C.voltage + drive_W1(56)*D.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*V_X_v + drive_W1(15)*A.voltage + drive_W1(29)*B.voltage + drive_W1(43)*C.voltage + drive_W1(57)*D.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*V_X_v + drive_W1(16)*A.voltage + drive_W1(30)*B.voltage + drive_W1(44)*C.voltage + drive_W1(58)*D.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*V_X_v + drive_W1(17)*A.voltage + drive_W1(31)*B.voltage + drive_W1(45)*C.voltage + drive_W1(59)*D.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*V_X_v + drive_W1(18)*A.voltage + drive_W1(32)*B.voltage + drive_W1(46)*C.voltage + drive_W1(60)*D.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*V_X_v + drive_W1(19)*A.voltage + drive_W1(33)*B.voltage + drive_W1(47)*C.voltage + drive_W1(61)*D.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*V_X_v + drive_W1(20)*A.voltage + drive_W1(34)*B.voltage + drive_W1(48)*C.voltage + drive_W1(62)*D.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*V_X_v + drive_W1(21)*A.voltage + drive_W1(35)*B.voltage + drive_W1(49)*C.voltage + drive_W1(63)*D.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*V_X_v + drive_W1(22)*A.voltage + drive_W1(36)*B.voltage + drive_W1(50)*C.voltage + drive_W1(64)*D.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*V_X_v + drive_W1(23)*A.voltage + drive_W1(37)*B.voltage + drive_W1(51)*C.voltage + drive_W1(65)*D.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*V_X_v + drive_W1(24)*A.voltage + drive_W1(38)*B.voltage + drive_W1(52)*C.voltage + drive_W1(66)*D.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*V_X_v + drive_W1(25)*A.voltage + drive_W1(39)*B.voltage + drive_W1(53)*C.voltage + drive_W1(67)*D.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        z_drive(12) := drive_W1(12)*V_X_v + drive_W1(26)*A.voltage + drive_W1(40)*B.voltage + drive_W1(54)*C.voltage + drive_W1(68)*D.voltage + drive_b1(12);
        if z_drive(12) > 0.0 then h_drive(12) := z_drive(12); else h_drive(12) := 0.01 * z_drive(12); end if;
        z_drive(13) := drive_W1(13)*V_X_v + drive_W1(27)*A.voltage + drive_W1(41)*B.voltage + drive_W1(55)*C.voltage + drive_W1(69)*D.voltage + drive_b1(13);
        if z_drive(13) > 0.0 then h_drive(13) := z_drive(13); else h_drive(13) := 0.01 * z_drive(13); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_W2(12)*h_drive(12) + drive_W2(13)*h_drive(13) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Digital inverter: V(Y) = NOT V(X) (same rule as hybrid_evt).
          if V_X_v > VTN then
            v_y := 0.0;
          else
            v_y := vdd_v;
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
