-- th34w2_nn_hybrid.vhd — NN-predicted drive current + analytical keeper.
--
-- Topology mirrors th22_hybrid_evt.vhd exactly. The IV-table lookup for
-- pull-up + pull-down is replaced by a small leaky-ReLU MLP:
--   drive_nn(V_X, V_A, V_B) → net pull-up+pull-down current into X
-- V(Y) is a digital inversion of V(X) (same rule as hybrid_evt) — the
-- inverter direction is deterministic from V(X), so no NN needed.
-- Hysteresis comes entirely from the hand-crafted analytical keeper
--   I_keep = (VDD - V(Y) - V(X)) / R_KEEP
-- which biases V(X) toward (VDD - V(Y)). When inputs are in a mixed
-- zone (one HIGH, one LOW) the NN predicts ~0 drive current and the
-- keeper holds V(X) at its previous rail.
--
-- Generated by /usr/local/src/ldx/asic/chr/extract_nn_hybrid.py

library ieee;
use ieee.math_real.all;
use work.logic3d_types_pkg.all;
use work.logic3ds_pkg.all;
use work.logic3da_pkg.all;

entity th34w2_nn_hybrid is
  port (
    A       : in  logic3da;
    B       : in  logic3da;
    C       : in  logic3da;
    D       : in  logic3da;
    VDD     : in  logic3da;
    VSS     : in  logic3da;
    Y_drv   : out logic3da;
    Y_cap   : out real;
    VDD_drv : out logic3da
  );
end entity;

architecture evt of th34w2_nn_hybrid is

  constant VTN     : real := 0.40;
  constant VTP_ABS : real := 0.35;

  constant R_OUT   : real := 1.05e4;   -- output inverter effective R
  constant R_KEEP  : real := 8.0e4;    -- analytical keeper
  constant R_STEP  : real := 3.0e4;    -- NN-current → Δv step size

  constant C_X     : real := 6.4e-15;
  constant C_Y     : real := 5.0e-15;

  function zone(v, vdd : real) return integer is
  begin
    if v < VTN then return 0;
    elsif v > vdd - VTP_ABS then return 2;
    else return 1;
    end if;
  end function;

  constant drive_W1 : real_vector(0 to 287) := (
    +4.300980e-02, +2.399913e-01, +5.926630e-01, -2.573093e-01, +2.243568e-01, +1.704771e-01,
    -3.118222e-01, -4.946423e-01, -1.443183e-01, -1.422329e+00, +2.856769e-01, +1.760929e-01,
    +1.275224e-01, +8.432252e-02, +9.220707e-01, +1.081282e-01, +7.644940e-02, -1.541767e-01,
    -4.473998e-01, -7.035325e-01, -5.541234e-01, +5.917948e-02, -2.955027e-02, +4.580062e-01,
    +1.383631e-01, +6.681113e-02, -7.568361e-01, +5.425921e-01, -3.568670e-02, -4.759648e-01,
    -4.658486e-01, -1.485032e+00, +8.886490e-01, +1.286958e-01, +1.035859e+00, +7.020679e-01,
    +1.680262e-01, +3.582657e-01, -2.268995e-01, +1.897186e-01, -8.230409e-01, -7.010224e-02,
    +8.261885e-02, -2.909961e-01, -4.425184e-03, -9.017278e-02, -1.408507e-01, -3.483664e-01,
    -2.538479e-01, +1.050668e+00, +1.292459e+00, -8.980589e-01, -4.277442e+00, +9.609327e-01,
    -9.169006e-01, +3.644275e+00, -2.570478e-02, +9.741272e+00, +3.024501e+00, -5.522724e+00,
    -5.571806e+00, -4.626194e+00, -1.581063e+00, -2.549959e-01, -2.087928e+00, -1.872492e-01,
    +2.597801e-01, +1.120219e+00, -3.912999e-01, -2.099099e+00, -1.035071e+00, -6.269286e+00,
    -1.386754e+00, -2.697055e+00, +3.819668e-01, +1.735748e-01, -6.353204e-02, -9.359272e-01,
    -5.774878e-02, +6.997728e+00, -1.864218e+00, -5.798364e+00, -2.116490e+00, -3.747586e-01,
    -1.142297e+00, -3.299304e+00, +7.020762e-01, -5.700412e+00, +6.639013e+00, +7.374670e+00,
    +7.091958e-01, +2.369180e+00, +5.243281e+00, +8.082802e-01, +3.554537e+00, -1.526450e+00,
    -7.265485e+00, +3.575277e+00, +2.931876e+00, -5.317664e-01, -8.477655e-01, -5.989323e+00,
    +1.089596e+01, +5.380010e+00, -2.459637e-01, -1.954806e+00, +1.901040e+00, +6.169807e+00,
    -5.971990e-01, -1.386687e+00, +1.539525e+00, +4.654160e+00, -1.293559e+00, +3.615728e-02,
    -1.659105e-01, -8.146810e-01, +7.585485e-02, -6.715659e-01, +1.636730e+00, +2.494579e+00,
    +2.674443e+00, -2.404763e+00, -3.773692e-02, -1.038297e-01, -3.559533e-01, +2.972187e+00,
    -6.465358e-01, +1.298419e+00, -4.747677e+00, +2.125758e-01, -4.158997e+00, +1.198596e+00,
    +3.701703e-01, -2.006818e+00, -5.672016e-01, +3.395459e+00, +7.333469e-01, -2.956979e+00,
    +5.347040e+00, -2.256320e+00, +4.535526e-01, -3.138396e+00, +2.556024e+00, +3.052808e+00,
    -3.808655e-03, +3.671287e-01, +3.039464e+00, -1.383232e-01, +3.051169e+00, -4.787853e-03,
    -6.831621e-01, -3.322080e-01, -1.793762e-01, -5.865680e-01, -6.834854e-01, -6.752701e-03,
    -3.839732e-01, -7.325588e-02, +2.142410e+00, +8.674134e-02, -1.443511e-01, -1.953143e-02,
    +2.948972e+00, -1.041841e+00, -5.309784e-02, -1.207151e+00, -3.568959e+00, +1.796707e+00,
    +1.461789e-01, +1.466519e-01, -2.165595e-01, +1.188312e-01, -1.016622e-01, -3.341632e-01,
    -3.014592e-01, +6.125726e-01, +4.763111e-01, +1.249623e-01, -1.085902e-01, +5.867590e-01,
    +1.835906e-01, -9.473464e-01, +2.737802e+00, +1.158697e+00, -2.746690e-02, -1.641465e+00,
    +6.643949e-02, +9.125830e-01, +5.621561e-01, +1.870569e+00, -1.729488e+00, +2.874033e+00,
    -7.756513e-02, +5.568737e-01, +3.802303e-01, +5.401783e-01, -6.572346e-02, +8.767630e-02,
    -1.856627e+00, -2.442059e-01, -3.769331e-01, -2.892893e-01, -5.018038e-01, -8.088924e-02,
    -3.909081e-01, +3.827868e+00, -2.291638e-01, -2.316553e+00, -2.173181e-01, -3.036351e-01,
    +5.957885e-01, +1.700347e+00, -4.896099e-01, -1.164094e+00, +7.812363e-02, +1.375074e+00,
    +1.374013e-01, +1.817643e+00, -2.556607e-01, -1.141953e-02, -3.116770e-02, -1.636595e+00,
    -4.832098e-01, +9.184959e-01, +3.810208e-01, +9.361397e-02, -1.476966e-01, +6.725649e-01,
    -2.816015e+00, -9.350125e-01, +2.303956e+00, +1.146524e+00, +2.605446e-01, -1.353589e+00,
    +3.316265e+00, -2.209323e+00, +4.658153e-01, -1.462285e-01, +1.296055e-01, +9.853507e-01,
    +6.008765e-01, +4.654549e+00, +4.072309e-01, -4.373585e-01, +1.921820e-02, +2.879887e+00,
    -9.781041e-01, -2.202684e+00, -2.103183e-01, -4.970421e+00, -2.504225e+00, +2.623592e-01,
    +4.175525e+00, -1.855103e-01, -1.233325e+00, -1.354216e-01, +2.619917e+00, +3.132671e-02,
    +7.731695e-01, +5.495964e-01, +1.476762e-02, +1.615648e+00, +3.386560e-01, +1.828620e+00,
    -3.402588e+00, +7.960975e-02, -2.026417e-01, +5.193714e+00, -3.640896e-01, -3.235762e-01,
    +7.000947e-03, -3.139799e+00, +5.460044e+00, +3.662058e+00, +2.814025e+00, +6.062520e+00,
    +6.122094e-01, -1.009899e+00, +2.784898e+00, +3.542523e+00, -3.574475e+00, -9.581999e-01,
    +2.880967e-01, +1.366875e+00, -7.131088e-01, +2.134715e-01, -1.546807e-01, +2.713009e+00
  );
  constant drive_b1 : real_vector(0 to 47) := (
    +4.958926e+00, -1.165449e+01, -9.448499e+00, -1.458093e-01, -1.424826e+00, +1.694603e+00,
    -6.786794e+00, -1.352263e+00, +1.537910e-03, -1.036842e+00, -7.927115e-01, -4.805857e+00,
    -7.653859e-01, -1.201569e+00, -1.744777e+00, -3.512375e+00, -1.935670e+00, -3.008067e-02,
    -5.124574e+00, -1.570771e+00, -4.443452e-04, +1.266192e+00, +4.424789e-01, -9.217497e+00,
    -2.999163e-01, -2.204785e-01, -6.301496e-04, -6.987995e+00, -1.278913e-02, -7.025068e-01,
    -2.504798e-03, -3.859259e+00, +2.101325e+00, -3.743350e+00, +2.862618e+00, -8.352876e+00,
    +6.373531e-01, +9.927443e-01, -9.368994e+00, -4.765395e+00, -1.550553e+00, +5.966365e+00,
    -1.149305e+01, +4.753492e-01, -5.723443e-01, +2.342734e-01, +1.380378e-01, -9.297768e+00
  );
  constant drive_W2 : real_vector(0 to 47) := (
    -4.251045e-05, -3.024997e-05, -2.192105e-05, +1.125322e-05, +2.358400e-05, +2.461317e-05,
    +2.716060e-05, -2.135266e-05, +9.766119e-07, -2.562626e-05, +1.059909e-05, +3.174310e-05,
    +2.716074e-05, +2.684138e-05, -9.038537e-06, -2.057100e-05, -2.831592e-05, +5.066953e-06,
    +2.825831e-05, +1.116262e-05, -6.399702e-07, -1.846546e-05, -1.598334e-05, +6.426833e-05,
    -1.396771e-05, -2.879038e-05, -7.241544e-07, +3.322671e-05, -4.528003e-06, -1.620932e-05,
    -2.288185e-06, +1.210852e-05, -1.802837e-05, +3.968720e-05, +1.631842e-05, -2.625836e-05,
    -1.396346e-05, +4.190287e-05, -3.681668e-05, -2.465878e-05, +2.285371e-05, +2.686936e-05,
    -3.261109e-05, -1.083099e-05, -2.136779e-05, +1.561274e-05, -1.747052e-05, -2.769097e-05
  );
  constant drive_b2 : real_vector(0 to 0) := (0 => +1.311111e-05);

  signal v_y_sig : real := 0.0;

begin

  eval : process
    variable z_a, z_b, z_c, z_d : integer := 0;
    variable z_a_new, z_b_new, z_c_new, z_d_new : integer;
    variable vdd_v            : real;
    variable V_X_v            : real := 0.0;  -- internal X node, persistent
    variable v_y              : real := 0.0;
    variable i_drive, i_keep  : real;
    variable i_supply         : real;
    variable z_drive, h_drive : real_vector(0 to 47);
    variable y_drive          : real;
  begin
    Y_drv   <= (voltage => 0.0, resistance => R_OUT, flags => AFL_KNOWN);
    Y_cap   <= C_Y;
    VDD_drv <= (voltage => 0.0, resistance => 1.0e9, flags => AFL_KNOWN);

    loop
      wait on A, B, C, D, VDD;

      vdd_v := VDD.voltage;
      z_a_new := zone(A.voltage, vdd_v);
      z_b_new := zone(B.voltage, vdd_v);
      z_c_new := zone(C.voltage, vdd_v);
      z_d_new := zone(D.voltage, vdd_v);

      if z_a_new /= z_a or z_b_new /= z_b or z_c_new /= z_c or z_d_new /= z_d then
        z_a := z_a_new;
        z_b := z_b_new;
        z_c := z_c_new;
        z_d := z_d_new;

        -- Newton-style iteration over V(X). At each step:
        --   1. Evaluate NN for i_drive(V_X, V_A, V_B)
        --   2. Evaluate analytical keeper i_keep(V_X, V_Y)
        --   3. Update V_X toward equilibrium: V_X += (i_drive + i_keep) * R_STEP
        -- Then apply digital inverter rule for V(Y). A few iterations
        -- suffice because the NN surface is approximately monotonic in V_X.
        for iter in 0 to 7 loop
        z_drive(0) := drive_W1(0)*vdd_v + drive_W1(48)*V_X_v + drive_W1(96)*A.voltage + drive_W1(144)*B.voltage + drive_W1(192)*C.voltage + drive_W1(240)*D.voltage + drive_b1(0);
        if z_drive(0) > 0.0 then h_drive(0) := z_drive(0); else h_drive(0) := 0.01 * z_drive(0); end if;
        z_drive(1) := drive_W1(1)*vdd_v + drive_W1(49)*V_X_v + drive_W1(97)*A.voltage + drive_W1(145)*B.voltage + drive_W1(193)*C.voltage + drive_W1(241)*D.voltage + drive_b1(1);
        if z_drive(1) > 0.0 then h_drive(1) := z_drive(1); else h_drive(1) := 0.01 * z_drive(1); end if;
        z_drive(2) := drive_W1(2)*vdd_v + drive_W1(50)*V_X_v + drive_W1(98)*A.voltage + drive_W1(146)*B.voltage + drive_W1(194)*C.voltage + drive_W1(242)*D.voltage + drive_b1(2);
        if z_drive(2) > 0.0 then h_drive(2) := z_drive(2); else h_drive(2) := 0.01 * z_drive(2); end if;
        z_drive(3) := drive_W1(3)*vdd_v + drive_W1(51)*V_X_v + drive_W1(99)*A.voltage + drive_W1(147)*B.voltage + drive_W1(195)*C.voltage + drive_W1(243)*D.voltage + drive_b1(3);
        if z_drive(3) > 0.0 then h_drive(3) := z_drive(3); else h_drive(3) := 0.01 * z_drive(3); end if;
        z_drive(4) := drive_W1(4)*vdd_v + drive_W1(52)*V_X_v + drive_W1(100)*A.voltage + drive_W1(148)*B.voltage + drive_W1(196)*C.voltage + drive_W1(244)*D.voltage + drive_b1(4);
        if z_drive(4) > 0.0 then h_drive(4) := z_drive(4); else h_drive(4) := 0.01 * z_drive(4); end if;
        z_drive(5) := drive_W1(5)*vdd_v + drive_W1(53)*V_X_v + drive_W1(101)*A.voltage + drive_W1(149)*B.voltage + drive_W1(197)*C.voltage + drive_W1(245)*D.voltage + drive_b1(5);
        if z_drive(5) > 0.0 then h_drive(5) := z_drive(5); else h_drive(5) := 0.01 * z_drive(5); end if;
        z_drive(6) := drive_W1(6)*vdd_v + drive_W1(54)*V_X_v + drive_W1(102)*A.voltage + drive_W1(150)*B.voltage + drive_W1(198)*C.voltage + drive_W1(246)*D.voltage + drive_b1(6);
        if z_drive(6) > 0.0 then h_drive(6) := z_drive(6); else h_drive(6) := 0.01 * z_drive(6); end if;
        z_drive(7) := drive_W1(7)*vdd_v + drive_W1(55)*V_X_v + drive_W1(103)*A.voltage + drive_W1(151)*B.voltage + drive_W1(199)*C.voltage + drive_W1(247)*D.voltage + drive_b1(7);
        if z_drive(7) > 0.0 then h_drive(7) := z_drive(7); else h_drive(7) := 0.01 * z_drive(7); end if;
        z_drive(8) := drive_W1(8)*vdd_v + drive_W1(56)*V_X_v + drive_W1(104)*A.voltage + drive_W1(152)*B.voltage + drive_W1(200)*C.voltage + drive_W1(248)*D.voltage + drive_b1(8);
        if z_drive(8) > 0.0 then h_drive(8) := z_drive(8); else h_drive(8) := 0.01 * z_drive(8); end if;
        z_drive(9) := drive_W1(9)*vdd_v + drive_W1(57)*V_X_v + drive_W1(105)*A.voltage + drive_W1(153)*B.voltage + drive_W1(201)*C.voltage + drive_W1(249)*D.voltage + drive_b1(9);
        if z_drive(9) > 0.0 then h_drive(9) := z_drive(9); else h_drive(9) := 0.01 * z_drive(9); end if;
        z_drive(10) := drive_W1(10)*vdd_v + drive_W1(58)*V_X_v + drive_W1(106)*A.voltage + drive_W1(154)*B.voltage + drive_W1(202)*C.voltage + drive_W1(250)*D.voltage + drive_b1(10);
        if z_drive(10) > 0.0 then h_drive(10) := z_drive(10); else h_drive(10) := 0.01 * z_drive(10); end if;
        z_drive(11) := drive_W1(11)*vdd_v + drive_W1(59)*V_X_v + drive_W1(107)*A.voltage + drive_W1(155)*B.voltage + drive_W1(203)*C.voltage + drive_W1(251)*D.voltage + drive_b1(11);
        if z_drive(11) > 0.0 then h_drive(11) := z_drive(11); else h_drive(11) := 0.01 * z_drive(11); end if;
        z_drive(12) := drive_W1(12)*vdd_v + drive_W1(60)*V_X_v + drive_W1(108)*A.voltage + drive_W1(156)*B.voltage + drive_W1(204)*C.voltage + drive_W1(252)*D.voltage + drive_b1(12);
        if z_drive(12) > 0.0 then h_drive(12) := z_drive(12); else h_drive(12) := 0.01 * z_drive(12); end if;
        z_drive(13) := drive_W1(13)*vdd_v + drive_W1(61)*V_X_v + drive_W1(109)*A.voltage + drive_W1(157)*B.voltage + drive_W1(205)*C.voltage + drive_W1(253)*D.voltage + drive_b1(13);
        if z_drive(13) > 0.0 then h_drive(13) := z_drive(13); else h_drive(13) := 0.01 * z_drive(13); end if;
        z_drive(14) := drive_W1(14)*vdd_v + drive_W1(62)*V_X_v + drive_W1(110)*A.voltage + drive_W1(158)*B.voltage + drive_W1(206)*C.voltage + drive_W1(254)*D.voltage + drive_b1(14);
        if z_drive(14) > 0.0 then h_drive(14) := z_drive(14); else h_drive(14) := 0.01 * z_drive(14); end if;
        z_drive(15) := drive_W1(15)*vdd_v + drive_W1(63)*V_X_v + drive_W1(111)*A.voltage + drive_W1(159)*B.voltage + drive_W1(207)*C.voltage + drive_W1(255)*D.voltage + drive_b1(15);
        if z_drive(15) > 0.0 then h_drive(15) := z_drive(15); else h_drive(15) := 0.01 * z_drive(15); end if;
        z_drive(16) := drive_W1(16)*vdd_v + drive_W1(64)*V_X_v + drive_W1(112)*A.voltage + drive_W1(160)*B.voltage + drive_W1(208)*C.voltage + drive_W1(256)*D.voltage + drive_b1(16);
        if z_drive(16) > 0.0 then h_drive(16) := z_drive(16); else h_drive(16) := 0.01 * z_drive(16); end if;
        z_drive(17) := drive_W1(17)*vdd_v + drive_W1(65)*V_X_v + drive_W1(113)*A.voltage + drive_W1(161)*B.voltage + drive_W1(209)*C.voltage + drive_W1(257)*D.voltage + drive_b1(17);
        if z_drive(17) > 0.0 then h_drive(17) := z_drive(17); else h_drive(17) := 0.01 * z_drive(17); end if;
        z_drive(18) := drive_W1(18)*vdd_v + drive_W1(66)*V_X_v + drive_W1(114)*A.voltage + drive_W1(162)*B.voltage + drive_W1(210)*C.voltage + drive_W1(258)*D.voltage + drive_b1(18);
        if z_drive(18) > 0.0 then h_drive(18) := z_drive(18); else h_drive(18) := 0.01 * z_drive(18); end if;
        z_drive(19) := drive_W1(19)*vdd_v + drive_W1(67)*V_X_v + drive_W1(115)*A.voltage + drive_W1(163)*B.voltage + drive_W1(211)*C.voltage + drive_W1(259)*D.voltage + drive_b1(19);
        if z_drive(19) > 0.0 then h_drive(19) := z_drive(19); else h_drive(19) := 0.01 * z_drive(19); end if;
        z_drive(20) := drive_W1(20)*vdd_v + drive_W1(68)*V_X_v + drive_W1(116)*A.voltage + drive_W1(164)*B.voltage + drive_W1(212)*C.voltage + drive_W1(260)*D.voltage + drive_b1(20);
        if z_drive(20) > 0.0 then h_drive(20) := z_drive(20); else h_drive(20) := 0.01 * z_drive(20); end if;
        z_drive(21) := drive_W1(21)*vdd_v + drive_W1(69)*V_X_v + drive_W1(117)*A.voltage + drive_W1(165)*B.voltage + drive_W1(213)*C.voltage + drive_W1(261)*D.voltage + drive_b1(21);
        if z_drive(21) > 0.0 then h_drive(21) := z_drive(21); else h_drive(21) := 0.01 * z_drive(21); end if;
        z_drive(22) := drive_W1(22)*vdd_v + drive_W1(70)*V_X_v + drive_W1(118)*A.voltage + drive_W1(166)*B.voltage + drive_W1(214)*C.voltage + drive_W1(262)*D.voltage + drive_b1(22);
        if z_drive(22) > 0.0 then h_drive(22) := z_drive(22); else h_drive(22) := 0.01 * z_drive(22); end if;
        z_drive(23) := drive_W1(23)*vdd_v + drive_W1(71)*V_X_v + drive_W1(119)*A.voltage + drive_W1(167)*B.voltage + drive_W1(215)*C.voltage + drive_W1(263)*D.voltage + drive_b1(23);
        if z_drive(23) > 0.0 then h_drive(23) := z_drive(23); else h_drive(23) := 0.01 * z_drive(23); end if;
        z_drive(24) := drive_W1(24)*vdd_v + drive_W1(72)*V_X_v + drive_W1(120)*A.voltage + drive_W1(168)*B.voltage + drive_W1(216)*C.voltage + drive_W1(264)*D.voltage + drive_b1(24);
        if z_drive(24) > 0.0 then h_drive(24) := z_drive(24); else h_drive(24) := 0.01 * z_drive(24); end if;
        z_drive(25) := drive_W1(25)*vdd_v + drive_W1(73)*V_X_v + drive_W1(121)*A.voltage + drive_W1(169)*B.voltage + drive_W1(217)*C.voltage + drive_W1(265)*D.voltage + drive_b1(25);
        if z_drive(25) > 0.0 then h_drive(25) := z_drive(25); else h_drive(25) := 0.01 * z_drive(25); end if;
        z_drive(26) := drive_W1(26)*vdd_v + drive_W1(74)*V_X_v + drive_W1(122)*A.voltage + drive_W1(170)*B.voltage + drive_W1(218)*C.voltage + drive_W1(266)*D.voltage + drive_b1(26);
        if z_drive(26) > 0.0 then h_drive(26) := z_drive(26); else h_drive(26) := 0.01 * z_drive(26); end if;
        z_drive(27) := drive_W1(27)*vdd_v + drive_W1(75)*V_X_v + drive_W1(123)*A.voltage + drive_W1(171)*B.voltage + drive_W1(219)*C.voltage + drive_W1(267)*D.voltage + drive_b1(27);
        if z_drive(27) > 0.0 then h_drive(27) := z_drive(27); else h_drive(27) := 0.01 * z_drive(27); end if;
        z_drive(28) := drive_W1(28)*vdd_v + drive_W1(76)*V_X_v + drive_W1(124)*A.voltage + drive_W1(172)*B.voltage + drive_W1(220)*C.voltage + drive_W1(268)*D.voltage + drive_b1(28);
        if z_drive(28) > 0.0 then h_drive(28) := z_drive(28); else h_drive(28) := 0.01 * z_drive(28); end if;
        z_drive(29) := drive_W1(29)*vdd_v + drive_W1(77)*V_X_v + drive_W1(125)*A.voltage + drive_W1(173)*B.voltage + drive_W1(221)*C.voltage + drive_W1(269)*D.voltage + drive_b1(29);
        if z_drive(29) > 0.0 then h_drive(29) := z_drive(29); else h_drive(29) := 0.01 * z_drive(29); end if;
        z_drive(30) := drive_W1(30)*vdd_v + drive_W1(78)*V_X_v + drive_W1(126)*A.voltage + drive_W1(174)*B.voltage + drive_W1(222)*C.voltage + drive_W1(270)*D.voltage + drive_b1(30);
        if z_drive(30) > 0.0 then h_drive(30) := z_drive(30); else h_drive(30) := 0.01 * z_drive(30); end if;
        z_drive(31) := drive_W1(31)*vdd_v + drive_W1(79)*V_X_v + drive_W1(127)*A.voltage + drive_W1(175)*B.voltage + drive_W1(223)*C.voltage + drive_W1(271)*D.voltage + drive_b1(31);
        if z_drive(31) > 0.0 then h_drive(31) := z_drive(31); else h_drive(31) := 0.01 * z_drive(31); end if;
        z_drive(32) := drive_W1(32)*vdd_v + drive_W1(80)*V_X_v + drive_W1(128)*A.voltage + drive_W1(176)*B.voltage + drive_W1(224)*C.voltage + drive_W1(272)*D.voltage + drive_b1(32);
        if z_drive(32) > 0.0 then h_drive(32) := z_drive(32); else h_drive(32) := 0.01 * z_drive(32); end if;
        z_drive(33) := drive_W1(33)*vdd_v + drive_W1(81)*V_X_v + drive_W1(129)*A.voltage + drive_W1(177)*B.voltage + drive_W1(225)*C.voltage + drive_W1(273)*D.voltage + drive_b1(33);
        if z_drive(33) > 0.0 then h_drive(33) := z_drive(33); else h_drive(33) := 0.01 * z_drive(33); end if;
        z_drive(34) := drive_W1(34)*vdd_v + drive_W1(82)*V_X_v + drive_W1(130)*A.voltage + drive_W1(178)*B.voltage + drive_W1(226)*C.voltage + drive_W1(274)*D.voltage + drive_b1(34);
        if z_drive(34) > 0.0 then h_drive(34) := z_drive(34); else h_drive(34) := 0.01 * z_drive(34); end if;
        z_drive(35) := drive_W1(35)*vdd_v + drive_W1(83)*V_X_v + drive_W1(131)*A.voltage + drive_W1(179)*B.voltage + drive_W1(227)*C.voltage + drive_W1(275)*D.voltage + drive_b1(35);
        if z_drive(35) > 0.0 then h_drive(35) := z_drive(35); else h_drive(35) := 0.01 * z_drive(35); end if;
        z_drive(36) := drive_W1(36)*vdd_v + drive_W1(84)*V_X_v + drive_W1(132)*A.voltage + drive_W1(180)*B.voltage + drive_W1(228)*C.voltage + drive_W1(276)*D.voltage + drive_b1(36);
        if z_drive(36) > 0.0 then h_drive(36) := z_drive(36); else h_drive(36) := 0.01 * z_drive(36); end if;
        z_drive(37) := drive_W1(37)*vdd_v + drive_W1(85)*V_X_v + drive_W1(133)*A.voltage + drive_W1(181)*B.voltage + drive_W1(229)*C.voltage + drive_W1(277)*D.voltage + drive_b1(37);
        if z_drive(37) > 0.0 then h_drive(37) := z_drive(37); else h_drive(37) := 0.01 * z_drive(37); end if;
        z_drive(38) := drive_W1(38)*vdd_v + drive_W1(86)*V_X_v + drive_W1(134)*A.voltage + drive_W1(182)*B.voltage + drive_W1(230)*C.voltage + drive_W1(278)*D.voltage + drive_b1(38);
        if z_drive(38) > 0.0 then h_drive(38) := z_drive(38); else h_drive(38) := 0.01 * z_drive(38); end if;
        z_drive(39) := drive_W1(39)*vdd_v + drive_W1(87)*V_X_v + drive_W1(135)*A.voltage + drive_W1(183)*B.voltage + drive_W1(231)*C.voltage + drive_W1(279)*D.voltage + drive_b1(39);
        if z_drive(39) > 0.0 then h_drive(39) := z_drive(39); else h_drive(39) := 0.01 * z_drive(39); end if;
        z_drive(40) := drive_W1(40)*vdd_v + drive_W1(88)*V_X_v + drive_W1(136)*A.voltage + drive_W1(184)*B.voltage + drive_W1(232)*C.voltage + drive_W1(280)*D.voltage + drive_b1(40);
        if z_drive(40) > 0.0 then h_drive(40) := z_drive(40); else h_drive(40) := 0.01 * z_drive(40); end if;
        z_drive(41) := drive_W1(41)*vdd_v + drive_W1(89)*V_X_v + drive_W1(137)*A.voltage + drive_W1(185)*B.voltage + drive_W1(233)*C.voltage + drive_W1(281)*D.voltage + drive_b1(41);
        if z_drive(41) > 0.0 then h_drive(41) := z_drive(41); else h_drive(41) := 0.01 * z_drive(41); end if;
        z_drive(42) := drive_W1(42)*vdd_v + drive_W1(90)*V_X_v + drive_W1(138)*A.voltage + drive_W1(186)*B.voltage + drive_W1(234)*C.voltage + drive_W1(282)*D.voltage + drive_b1(42);
        if z_drive(42) > 0.0 then h_drive(42) := z_drive(42); else h_drive(42) := 0.01 * z_drive(42); end if;
        z_drive(43) := drive_W1(43)*vdd_v + drive_W1(91)*V_X_v + drive_W1(139)*A.voltage + drive_W1(187)*B.voltage + drive_W1(235)*C.voltage + drive_W1(283)*D.voltage + drive_b1(43);
        if z_drive(43) > 0.0 then h_drive(43) := z_drive(43); else h_drive(43) := 0.01 * z_drive(43); end if;
        z_drive(44) := drive_W1(44)*vdd_v + drive_W1(92)*V_X_v + drive_W1(140)*A.voltage + drive_W1(188)*B.voltage + drive_W1(236)*C.voltage + drive_W1(284)*D.voltage + drive_b1(44);
        if z_drive(44) > 0.0 then h_drive(44) := z_drive(44); else h_drive(44) := 0.01 * z_drive(44); end if;
        z_drive(45) := drive_W1(45)*vdd_v + drive_W1(93)*V_X_v + drive_W1(141)*A.voltage + drive_W1(189)*B.voltage + drive_W1(237)*C.voltage + drive_W1(285)*D.voltage + drive_b1(45);
        if z_drive(45) > 0.0 then h_drive(45) := z_drive(45); else h_drive(45) := 0.01 * z_drive(45); end if;
        z_drive(46) := drive_W1(46)*vdd_v + drive_W1(94)*V_X_v + drive_W1(142)*A.voltage + drive_W1(190)*B.voltage + drive_W1(238)*C.voltage + drive_W1(286)*D.voltage + drive_b1(46);
        if z_drive(46) > 0.0 then h_drive(46) := z_drive(46); else h_drive(46) := 0.01 * z_drive(46); end if;
        z_drive(47) := drive_W1(47)*vdd_v + drive_W1(95)*V_X_v + drive_W1(143)*A.voltage + drive_W1(191)*B.voltage + drive_W1(239)*C.voltage + drive_W1(287)*D.voltage + drive_b1(47);
        if z_drive(47) > 0.0 then h_drive(47) := z_drive(47); else h_drive(47) := 0.01 * z_drive(47); end if;
        y_drive := drive_W2(0)*h_drive(0) + drive_W2(1)*h_drive(1) + drive_W2(2)*h_drive(2) + drive_W2(3)*h_drive(3) + drive_W2(4)*h_drive(4) + drive_W2(5)*h_drive(5) + drive_W2(6)*h_drive(6) + drive_W2(7)*h_drive(7) + drive_W2(8)*h_drive(8) + drive_W2(9)*h_drive(9) + drive_W2(10)*h_drive(10) + drive_W2(11)*h_drive(11) + drive_W2(12)*h_drive(12) + drive_W2(13)*h_drive(13) + drive_W2(14)*h_drive(14) + drive_W2(15)*h_drive(15) + drive_W2(16)*h_drive(16) + drive_W2(17)*h_drive(17) + drive_W2(18)*h_drive(18) + drive_W2(19)*h_drive(19) + drive_W2(20)*h_drive(20) + drive_W2(21)*h_drive(21) + drive_W2(22)*h_drive(22) + drive_W2(23)*h_drive(23) + drive_W2(24)*h_drive(24) + drive_W2(25)*h_drive(25) + drive_W2(26)*h_drive(26) + drive_W2(27)*h_drive(27) + drive_W2(28)*h_drive(28) + drive_W2(29)*h_drive(29) + drive_W2(30)*h_drive(30) + drive_W2(31)*h_drive(31) + drive_W2(32)*h_drive(32) + drive_W2(33)*h_drive(33) + drive_W2(34)*h_drive(34) + drive_W2(35)*h_drive(35) + drive_W2(36)*h_drive(36) + drive_W2(37)*h_drive(37) + drive_W2(38)*h_drive(38) + drive_W2(39)*h_drive(39) + drive_W2(40)*h_drive(40) + drive_W2(41)*h_drive(41) + drive_W2(42)*h_drive(42) + drive_W2(43)*h_drive(43) + drive_W2(44)*h_drive(44) + drive_W2(45)*h_drive(45) + drive_W2(46)*h_drive(46) + drive_W2(47)*h_drive(47) + drive_b2(0);
          i_drive := y_drive;
          i_keep  := (vdd_v - v_y - V_X_v) / R_KEEP;

          V_X_v := V_X_v + (i_drive + i_keep) * R_STEP;
          if V_X_v > vdd_v then V_X_v := vdd_v; end if;
          if V_X_v < 0.0   then V_X_v := 0.0;   end if;

          -- Inverter rule with HOLD zone (completion detection). Only
          -- commit V(Y) to a rail when V(X) is clearly past the PMOS/NMOS
          -- threshold. In between (ACTIVE zone) keep the previous v_y —
          -- this is the event-driven analogue of "the physical inverter
          -- is still mid-transition, so the downstream gate shouldn't
          -- see a new rail yet". Without this the cell snaps to a rail
          -- on every partial input change and the keeper locks it in
          -- prematurely, breaking multi-stage NCL cascades.
          if V_X_v < VTN then
            v_y := vdd_v;
          elsif V_X_v > vdd_v - VTP_ABS then
            v_y := 0.0;
          -- else: hold previous v_y
          end if;
        end loop;

        i_supply := abs(i_drive) + abs(i_keep);

        v_y_sig <= v_y;
        Y_drv <= (voltage => v_y, resistance => R_OUT, flags => AFL_KNOWN);
        Y_cap <= C_Y;
        if vdd_v > 0.01 then
          VDD_drv <= (voltage => 0.0,
                      resistance => vdd_v / (i_supply + 1.0e-12),
                      flags => AFL_KNOWN);
        end if;
      end if;
    end loop;
  end process;

end architecture;
