#!/usr/bin/env python3
"""seed_from_behavioral.py — run the behavioral version of a SPICE testbench
to generate initial conditions for the analog (transistor-level) version.

Workflow:
  1. Read <tb>.sp, swap TH-cell includes to the ideal behavioral library
     (cells/th_ideal.sp). No transistors, so DCOP converges trivially.
  2. Run Xyce with a short transient; record every top-level net.
  3. At the requested seed time (default t=0 = NULL state), snapshot all
     node voltages.
  4. Emit a .IC preamble that can be prepended to the analog netlist.

Usage:
  python3 seed_from_behavioral.py <tb.sp> [--at-ns=0] [--out=seed.sp]
"""

import argparse, csv, os, re, subprocess, sys, shutil

XYCE = "/usr/local/src/Xyce-8/xyce-build/src/Xyce"
PSP_PLUGIN = "/usr/local/src/kestrel/sim/psp103_sg13g2.so"
CELLS = "/usr/local/src/ldx/asic/cells"

BEHAVIORAL_REPLACEMENTS = {
    # Swap transistor-level TH library for ideal behavioral.
    os.path.join(CELLS, "th22.sp"):     os.path.join(CELLS, "th_ideal.sp"),
    os.path.join(CELLS, "th_gates.sp"): None,  # absorbed into th_ideal.sp
}


def rewrite_as_behavioral(tb_path, beh_path):
    """Read tb_path, produce beh_path with TH includes swapped to th_ideal.sp."""
    seen_ideal = False
    lines = []
    with open(tb_path) as f:
        for line in f:
            stripped = line.strip()
            # Drop the PSP model include — no transistors in behavioral version.
            if "sg13g2_models.lib" in stripped:
                lines.append("* [seed] dropped model include\n")
                continue
            m = re.match(r'\s*\.include\s+"([^"]+)"', stripped)
            if m:
                path = m.group(1)
                if path in BEHAVIORAL_REPLACEMENTS:
                    target = BEHAVIORAL_REPLACEMENTS[path]
                    if target is None:
                        lines.append(f"* [seed] dropped {path}\n")
                        continue
                    if seen_ideal:
                        lines.append(f"* [seed] dropped duplicate include for {path}\n")
                        continue
                    lines.append(f'.include "{target}"\n')
                    seen_ideal = True
                    continue
            # Shorten the sim window — only need DCOP + first few ns.
            tm = re.match(r'\s*\.tran\s+(\S+)\s+(\S+)', stripped, re.IGNORECASE)
            if tm:
                lines.append(f"* [seed] original: {stripped}\n")
                lines.append(f".tran {tm.group(1)} 5n\n")
                continue
            # Replace .print with a "print everything" version.
            if re.match(r'\s*\.print\s+tran', stripped, re.IGNORECASE):
                lines.append(f"* [seed] dropped original: {stripped}\n")
                continue
            lines.append(line)
    # Inject all-node print just before .end
    new_lines = []
    inserted = False
    for line in lines:
        if not inserted and line.strip().lower() == ".end":
            new_lines.append(".print tran format=csv V(*)\n")
            inserted = True
        new_lines.append(line)
    if not inserted:
        new_lines.append(".print tran format=csv V(*)\n")
    lines = new_lines
    with open(beh_path, "w") as f:
        f.writelines(lines)


def run_xyce(path):
    # The plugin isn't needed (no PSP devices), but harmless.
    r = subprocess.run([XYCE, path], capture_output=True, text=True)
    if r.returncode != 0 or "Xyce Abort" in r.stdout:
        print("behavioral sim stdout tail:\n", r.stdout[-1500:])
        raise RuntimeError("behavioral Xyce aborted")
    return path + ".csv"


def snapshot_at(csv_path, t_ns):
    with open(csv_path) as f:
        rows = list(csv.reader(f))
    hdr = [h.strip() for h in rows[0]]
    # Find the row at or just after the target time.
    t_target = t_ns * 1e-9
    for r in rows[1:]:
        if float(r[0]) >= t_target:
            return hdr, [float(x) for x in r]
    return hdr, [float(x) for x in rows[-1]]


def emit_ic(hdr, vals, out_path, t_ns):
    with open(out_path, "w") as f:
        f.write(f"* Initial conditions seeded from behavioural sim at t={t_ns}ns\n")
        f.write("* Generated by seed_from_behavioral.py — prepend to the analog netlist\n")
        f.write("*\n")
        n_written = 0
        for h, v in zip(hdr, vals):
            if h.upper().startswith("TIME"):
                continue
            m = re.match(r"V\((.+)\)$", h.strip(), re.IGNORECASE)
            if not m:
                continue
            node = m.group(1)
            if node.upper() in ("VDD", "VSS"):
                continue
            f.write(f".IC V({node})={v:.6e}\n")
            n_written += 1
    return n_written


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tb", help="Path to the analog transient testbench (.sp)")
    ap.add_argument("--at-ns", type=float, default=0.1,
                    help="Seed time in ns (default 0.1 — beginning of NULL)")
    ap.add_argument("--out", default=None,
                    help="Output .IC file (default: <tb_basename>.ic.sp)")
    args = ap.parse_args()

    tb_path = os.path.abspath(args.tb)
    base, _ = os.path.splitext(tb_path)
    beh_path = base + ".beh.sp"
    ic_path = args.out or (base + ".ic.sp")

    print(f"[1/3] Rewriting as behavioural: {beh_path}")
    rewrite_as_behavioral(tb_path, beh_path)

    print(f"[2/3] Running behavioural sim")
    csv_path = run_xyce(beh_path)
    print(f"       CSV: {csv_path}")

    print(f"[3/3] Snapshotting at t={args.at_ns} ns → {ic_path}")
    hdr, vals = snapshot_at(csv_path, args.at_ns)
    n = emit_ic(hdr, vals, ic_path, args.at_ns)
    print(f"       Wrote {n} .IC statements")


if __name__ == "__main__":
    main()
