// Auto-generated cycle-based state machine from /tmp/cnt32.v
// Generated by gen_statemachine via Yosys RTLIL

#include <stdint.h>
#include <stdio.h>

typedef struct {
    uint64_t _inc;  // 32 bits
} inputs_t;

typedef struct {
    uint64_t _acc;  // 32 bits
} state_t;

typedef struct {
    uint64_t _acc;  // 32 bits
} outputs_t;

void sm_reset(state_t *s) {
    s->_acc = UINT64_C(0x0);
}

void sm_eval(state_t *s, const inputs_t *in, outputs_t *o) {
    // Input aliases
    uint64_t _inc = in->_inc;
    uint64_t _rst = 0;  // clock/reset handled externally
    uint64_t _clk = 0;  // clock/reset handled externally

    // Register aliases (current state)
    uint64_t _acc = s->_acc;

    // Combinational wires
    uint64_t _add__tmp_cnt32_v_2_2_Y = 0;

    // Combinational evaluation (topologically sorted)
#line 2 "/tmp/cnt32.v"
    _add__tmp_cnt32_v_2_2_Y = (_acc + _inc) & UINT64_C(0xffffffff);

    // Register updates (next state)
#line 2 "/tmp/cnt32.v"
    s->_acc = _add__tmp_cnt32_v_2_2_Y;

    // Outputs
    o->_acc = _acc;
}

#ifndef SM_NO_MAIN
int main(void) {
    state_t s;
    inputs_t in = {0};
    outputs_t o;
    int cycles = 2000000;
    sm_reset(&s);
    for (int i = 0; i < cycles; i++)
        sm_eval(&s, &in, &o);
    printf("Cycles: %d\n", cycles);
    printf("_acc: %08x\n", (unsigned)o._acc);
    return 0;
}
#endif // SM_NO_MAIN
