/* mb_m3c0.c — M3c.0: recompile the --accel/yosys state machine for the array.
 * The design's compute is sm_eval() (from cnt32_sm.c, generated by yosys). The
 * placement map (m3c0_map.h) says where the state lives in BRAM and what drives
 * the inputs. Node 0 runs the design + $displays its output each cycle; other
 * nodes just engage the barrier so it can advance. */
#include "mailbox.h"
#define SM_NO_MAIN 1
#include "cnt32_sm.c"        /* sm_eval, sm_reset, state_t, inputs_t, outputs_t */
#include "m3c0_map.h"        /* MAP_STATE_ADDR, MAP_INIT_INPUTS, MAP_DISPLAY_EXPR, MAP_DISP_HANDLE */

void main(void){
    uint32_t id = (mb_my_y()*2u) + mb_my_x();   /* ARRAY_X = 2 */
    if (id == 0u){
        state_t  *S = (state_t *)MAP_STATE_ADDR; /* registers live in BRAM */
        inputs_t  in; outputs_t o;
        MAP_INIT_INPUTS(in);                     /* drive the design's inputs (map) */
        sm_reset(S);
        for(;;){
            MB_CORE_BUSY = 1u;
            uint32_t c0 = MB_CYCLE_CNT;
            sm_eval(S, &in, &o);                 /* the accel/yosys compute */
            mb_display(MAP_DISP_HANDLE, (uint32_t)MAP_DISPLAY_EXPR(o));
            MB_CORE_BUSY = 0u;
            while (MB_CYCLE_CNT == c0){}
        }
    } else {                                      /* engage the barrier, no work */
        for(;;){ MB_CORE_BUSY = 1u; uint32_t c0 = MB_CYCLE_CNT; MB_CORE_BUSY = 0u;
                 while (MB_CYCLE_CNT == c0){} }
    }
}
