/* mb_m3c1.c — M3c.1: one design split across 2 cores, the crossing net routed
 * over the mailbox. Two accel/yosys partitions (producer, consumer) are included
 * with distinct prefixes (preprocessor namespacing — the array broadcasts ONE
 * program, so both partitions live in it and main() dispatches on node id).
 *
 * The crossing net is identified by each partition's sm_ports[] table: producer
 * has output "X", consumer has input "X" (and output "RESULT"). The codegen reads
 * those names/directions and wires the matching struct fields directly — producer
 * posts o._x, consumer deposits into in._x and displays o._result. (Direct field
 * access; the runtime-offset variant miscompiles under -Os when eval is inlined.) */
#include "mailbox.h"

/* --- producer partition (prefix p_) --- */
#define state_t p_state_t
#define inputs_t p_inputs_t
#define outputs_t p_outputs_t
#define sm_eval p_eval
#define sm_reset p_reset
#define sm_ports p_ports
#define sm_n_ports p_n_ports
#define sm_port_t p_port_t
#define SM_NO_MAIN 1
#include "producer_sm.c"
#undef state_t
#undef inputs_t
#undef outputs_t
#undef sm_eval
#undef sm_reset
#undef sm_ports
#undef sm_n_ports
#undef sm_port_t

/* --- consumer partition (prefix c_) --- */
#define state_t c_state_t
#define inputs_t c_inputs_t
#define outputs_t c_outputs_t
#define sm_eval c_eval
#define sm_reset c_reset
#define sm_ports c_ports
#define sm_n_ports c_n_ports
#define sm_port_t c_port_t
#include "consumer_sm.c"
#undef state_t
#undef inputs_t
#undef outputs_t
#undef sm_eval
#undef sm_reset
#undef sm_ports
#undef sm_n_ports
#undef sm_port_t

#include "m3c_map.h"   /* generated by genmap.py — m3c1.map (hand) or m3c2.map (auto) */

static uint32_t recv_word(void){
    while (MB_READY==0u){}
    uint32_t slot=mb_lowbit(MB_READY); uint32_t v=MB_SLOT(slot,1); MB_DONE=slot; return v;
}

void main(void){
    uint32_t id = (mb_my_y()*2u) + mb_my_x();   /* ARRAY_X=2 */
    if (id == 0u){                               /* producer: output port X = o._x */
        p_state_t *S = (p_state_t *)P_STATE_ADDR;
        p_inputs_t in; p_outputs_t o;
        p_reset(S);
        for(;;){
            MB_CORE_BUSY=1u; uint32_t c0=MB_CYCLE_CNT;
            p_eval(S, &in, &o);
            mb_post1(CONS_Y, CONS_X, (uint32_t)o._x);   /* crossing net X -> consumer */
            MB_CORE_BUSY=0u; while(MB_CYCLE_CNT==c0){}
        }
    } else {                                     /* consumer: input X = in._x, output RESULT */
        c_state_t *S = (c_state_t *)C_STATE_ADDR;
        c_inputs_t in; c_outputs_t o;
        c_reset(S);
        for(;;){
            MB_CORE_BUSY=1u; uint32_t c0=MB_CYCLE_CNT;
            in._x = recv_word();                 /* deposit crossing net X */
            c_eval(S, &in, &o);
            mb_display(DISP_HANDLE, (uint32_t)o._result);   /* $display(result) -> ARM */
            MB_CORE_BUSY=0u; while(MB_CYCLE_CNT==c0){}
        }
    }
}
