// accel_slot.v — Generic wrapper for c2v-generated combinational modules.
//
// Register-mapped interface:
//   Offset 0x00..0x3C: argument registers (up to 16 × 32-bit)
//   Offset 0x40:       result register (read-only, low 32 bits)
//   Offset 0x44:       result register (read-only, high 32 bits, for 64-bit returns)
//   Offset 0x48:       status (bit 0 = valid — always 1 for combinational)
//
// The c2v module is purely combinational: inputs change → output updates
// in the same cycle.  No start/done handshake needed.
//
// Parameters:
//   N_ARGS     — number of 32-bit argument registers
//   RET_WIDTH  — width of the result in bits (max 64)

module accel_slot #(
    parameter N_ARGS    = 2,
    parameter RET_WIDTH = 32
) (
    input  wire        clk,
    input  wire        reset_n,

    // Avalon-MM slave
    input  wire [5:0]  avs_address,     // word address (0..63)
    input  wire        avs_read,
    input  wire        avs_write,
    input  wire [31:0] avs_writedata,
    output reg  [31:0] avs_readdata,
    output wire        avs_waitrequest
);

    // No wait states — always ready
    assign avs_waitrequest = 1'b0;

    // Argument registers
    reg [31:0] arg_reg [0:N_ARGS-1];

    // c2v module ports (directly wired)
    wire [N_ARGS*32-1:0] args_flat;
    wire [RET_WIDTH-1:0] result;

    // Pad result to 64 bits so high-word read is always valid Verilog
    wire [63:0] result_pad = {{(64-RET_WIDTH){1'b0}}, result};

    // Flatten arg registers into a bus for the c2v module
    genvar i;
    generate
        for (i = 0; i < N_ARGS; i = i + 1) begin : flatten
            assign args_flat[i*32 +: 32] = arg_reg[i];
        end
    endgenerate

    // ---- c2v module instantiation ----
    // This file is generated by `c2v --fpga` and wires the c2v
    // combinational module's ports to arg_reg[] and result.
    `include "accel_slot_inst.v"

    // Write: store into argument registers
    integer j;
    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            for (j = 0; j < N_ARGS; j = j + 1)
                arg_reg[j] <= 32'd0;
        end else if (avs_write) begin
            if (avs_address < N_ARGS)
                arg_reg[avs_address] <= avs_writedata;
        end
    end

    // Read: return args, result, or status
    always @(*) begin
        if (avs_address < N_ARGS)
            avs_readdata = arg_reg[avs_address];
        else if (avs_address == 6'h10)  // 0x40 >> 2
            avs_readdata = result_pad[31:0];
        else if (avs_address == 6'h11)  // 0x44 >> 2
            avs_readdata = result_pad[63:32];
        else if (avs_address == 6'h12)  // 0x48 >> 2
            avs_readdata = 32'd1;       // always valid (combinational)
        else
            avs_readdata = 32'd0;
    end

endmodule
