-- NCL (async) version of add
-- Generated by c2v --ncl
library IEEE;
use IEEE.std_logic_1164.all;
library async_ncl;
use async_ncl.ncl.all;

entity add_ncl is
  port (
    a : in ncl_logic_vector(31 downto 0);
    b : in ncl_logic_vector(31 downto 0);
    result : out ncl_logic_vector(31 downto 0)
  );
end entity add_ncl;

architecture ncl_comb of add_ncl is
begin
  result <= ncl_add(a, b);
end architecture ncl_comb;
