-- NCL (async) version of bitwise_blend
-- Generated by c2v --ncl
library IEEE;
use IEEE.std_logic_1164.all;
library async_ncl;
use async_ncl.ncl.all;

entity bitwise_blend_ncl is
  port (
    a : in ncl_logic_vector(63 downto 0);
    b : in ncl_logic_vector(63 downto 0);
    mask : in ncl_logic_vector(63 downto 0);
    result : out ncl_logic_vector(63 downto 0)
  );
end entity bitwise_blend_ncl;

architecture ncl_comb of bitwise_blend_ncl is
begin
  result <= ((a and mask) or (b and (not mask)));
end architecture ncl_comb;
