-- NCL (async) version of max
-- Generated by c2v --ncl
library IEEE;
use IEEE.std_logic_1164.all;
library async_ncl;
use async_ncl.ncl.all;

entity max_ncl is
  port (
    a : in ncl_logic_vector(31 downto 0);
    b : in ncl_logic_vector(31 downto 0);
    result : out ncl_logic_vector(31 downto 0)
  );
end entity max_ncl;

architecture ncl_comb of max_ncl is
begin
  result <= ncl_mux(ncl_compare(a, b, ">"), a, b);
end architecture ncl_comb;
