# de2i_150.sdc — Timing constraints for ldx on DE2i-150.

# PCIe reference clock — 100 MHz
create_clock -name pcie_refclk -period 10.000 [get_ports pcie_refclk]

# PCIe core clock — 125 MHz (generated by hard IP, derived from refclk)
# The hard IP generates this internally; we constrain the user logic side.
derive_pll_clocks
derive_clock_uncertainty

# All paths in the accelerator are combinational within a single clock domain,
# so no special multicycle or false path constraints are needed.
